### PR TITLE
[Bug] Fix TypeError if input for getRegDataType is undefined

### PR DESCRIPTION
**Pull request by Nocccer**
Should fix this problem reported here:
https://discord.com/channels/812703221789097985/1061633792823001098

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by imLinguin** [comment]
Let's explore this issue more, maybe we should default to some type when it's not provided

**Comment by CommandMC** [comment]
`reg` uses `REG_SZ` as a default type, I assume the same is intended here

**Comment by imLinguin** [comment]
Here is the instruction it fails on

```json
{
            "install": {
                "action": "setRegistry",
                "arguments": {
                    "deleteSubkeys": true,
                    "root": "HKEY_LOCAL_MACHINE",
                    "saveGameData": true,
                    "subkey": "Software\\Microsoft\\Games\\Outwars"
                }
            },
            "languages": [
                "*"
            ],
            "name": "r01"
        },
```
Not sure what `saveGameData` means, but I think we should ignore that for now. This PR should suffice for now, in the future we will switch to `scriptinterpreter.exe` nevertheless

**Review by imLinguin — APPROVED** [review]

**Comment by imLinguin** [comment]
We may also consider this case

```json

{
            "install": {
                "action": "setRegistry",
                "arguments": {
                    "root": "HKEY_LOCAL_MACHINE",
                    "subkey": "Software\\Microsoft\\Games\\Outwars\\1.0.0",
                    "valueData": "",
                    "valueName": "IS UninstallString",
                    "velueType": "string"
                }
            },
            "languages": [
                "*"
            ],
            "name": "r18"
        },

```
Where `valueData` is empty

**Pull request merged**
