### PR TITLE
[UI] Fix install size on game page

### PR DESCRIPTION
**Pull request by matchuek**
show total used disk space from gameinfo manifest after updating a game

- [X] Tested the feature and it's working on a current and clean install.
- [X] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)

### CODE REVIEW

**Comment by arielj** [comment]
looks like `installSize` is the size in the manifest and `install_size` is the size reported by legendary for the installed game

is this issue happening ONLY for fortnite? can you check what's the install size of fortnite in legendary's `installed.json` file?

**Comment by matchuek** [comment]
Hi,

> can you check what's the install size of fortnite in legendary's `installed.json` file?

yeah, you're right:
`    "install_size": 0,`

> is this issue happening ONLY for fortnite?

Yes for me...

**Comment by flavioislima** [comment]
is this working? should we merge it to close it?

**Comment by matchuek** [comment]
This is not a heroic issue as discussed in #2492

**Pull request closed without merging**
