### PR TITLE
Try to fix macOS not launching CX

### PR DESCRIPTION
**Pull request by CommandMC**
---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by flavioislima** [comment]
Did you confirm that this is still an issue on macOS? 
I will do some tests disabling the shell again to see if it will break.

**Comment by CommandMC** [comment]
There are a bunch of people in the macOS channel having this issue, so I'd assume that it's still present
Sadly I nuked my macOS VM yesterday by accident, will need some time to get that setup again to test

**Comment by flavioislima** [comment]
I mean, I am testing here by using the shell on mac again to try to reproduce the first issue we had.
Because after that we had several refactors that might could have fixed the issue.

**Comment by flavioislima** [comment]
So far, removing the `shell: isMac` when running the command and this works:
- Install Epic game
- Install GOG game
- play windows games
- play native games
- play windows version of native games
- update a game (could test only on GOGDL since I don't have games to update on epic) is broken, even with latest test version of gogdl. But the command is being called so heroic is doing its part.
- Uninstall a game
- Login for both platform

So I believe it is 100% safe to remove the shell on macOS now. Could not find one single issue with the command call.

**Comment by CommandMC** [comment]
Alright, shell's removed now

With the last commit, I believe I've also fixed a bug: When you had an environment variable defined in both your process's env (so for example in .bashrc) and in Heroic's Settings, the process one would override Heroic's settings. That's now the other way around, which I think makes more sense

**Review by flavioislima — APPROVED** [review]
Looks good! 👍🏽

**Comment by flavioislima** [comment]
> Alright, shell's removed now
> 
> With the last commit, I believe I've also fixed a bug: When you had an environment variable defined in both your process's env (so for example in .bashrc) and in Heroic's Settings, the process one would override Heroic's settings. That's now the other way around, which I think makes more sense

yes, exactly, the latest override the first inside an object.

**Pull request merged**
