### PR TITLE
Refactor legendary setup

### PR DESCRIPTION
**Pull request by Etaash-mathamsetty**
~~created this PR early when wine-ge 8.x (or proton 8) eventually releases~~
it's released

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [x] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by guihkx** [comment]
(I just found this PR 'by accident', so please disregard this comment if I don't make any sense).

If I understand correctly, this is only applicable for Proton 8, right? But doesn't Heroic allow changing the Proton version freely? What would happen if the user manually downgraded their Proton version and tried to run Ubisoft Connect?

**Comment by Etaash-mathamsetty** [comment]
> (I just found this PR 'by accident', so please disregard this comment if I don't make any sense).
> 
> If I understand correctly, this is only applicable for Proton 8, right? But doesn't Heroic allow changing the Proton version freely? What would happen if the user manually downgraded their Proton version and tried to run Ubisoft Connect?

proton ships fonts already, so that's not a problem, and users should be using wine-ge 8.0 when that releases. (it will be pretty well regression tested since valve is taking forever to release proton 8)

**Comment by Etaash-mathamsetty** [comment]
this became relevant way sooner than expected :0

**Comment by Etaash-mathamsetty** [comment]
this is now relevant! (wine-ge 8.0 has released)

**Comment by arielj** [comment]
Maybe we should add a conditional for now to ignore this if wine 8? I know after the proton 8 release there was an issue with Elden Ring, I if it's better to just ignore the installation if 8 and if anybody needs to use 7 for any reason (who knows) this would still work

**Comment by flavioislima** [comment]
I think it is fine to install that on wine 8, it is just a font anyway. I don't think it will cause any harm and adding a `wine --version` check will slow down the process as well.

Perhaps once Wine-GE is more stable in the future we can get back to this but for now this is too hasty imo.

**Comment by Etaash-mathamsetty** [comment]
ok tested with wine-ge (it needed WINE_FSYNC_SIMULATE_SCHED_QUANTUM=1 to run), and I can confirm that it works without installing the arial font

**Comment by Etaash-mathamsetty** [comment]
I think this can get merged now, considering wine-ge can run ubisoft connect flawlessly now ootb

**Comment by Etaash-mathamsetty** [comment]
it's been a few months, I think we could potentially merge this after 2.9.1

**Review by arielj — APPROVED** [review]
Looks good to me, I tested installing/playing a ubisoft game and fallout new vegas.

**Pull request merged**
