### PR TITLE
[EPIC] Login with preload script

### PR DESCRIPTION
**Pull request by arielj**
This PR is a replacement of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/1762

I think I found a simpler approach. Instead of overriding the epic functions, the injected JS just adds an `onload` function that, when the expected json response is present, will send a message to the host (the react app) with the code.

It is similar to the current login method but we don't rely on `find-in-page` and we don't mess with the user's clipboard.

The only thing I'm not sure about is that I was not able to make the `contextBridge.exposeInMainWorld` code work so I can't seem to hide the ipcRenderer under a function, but I'm only using it in a callback so I think it's still isolated?

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by derrod** [comment]
I think you forgot the preload script.

But it's also worth noting that the reason to emulate the launcher was to allow for third-party logins (Google, Nintendo, Facebook, etc.) which may block Electron itself (Google does at least).

**Comment by arielj** [comment]
> I think you forgot the preload script.

oh right, I think it's gitignored, I'll check that

> But it's also worth noting that the reason to emulate the launcher was to allow for third-party logins (Google, Nintendo, Facebook, etc.) which may block Electron itself (Google does at least).

hmmm good point, I only tested the normal email+password login, I'll see what happens when I try to log in using one of the other methods

**Comment by arielj** [comment]
@derrod not sure if I'm missing something, I did try to login using Gmail for example and it works since after the Google login process it takes me to the same page with the authorization code json response (I have to login to Gmail inside Heroic, but that's how it's currently in the stable release too)

I added the preload js file to the PR

**Review by Nocccer — APPROVED** [review]
Tested it with google login and it worked.

**Review by flavioislima — CHANGES_REQUESTED** [review]
Tested here, codewise looks good but I think heroic cannot find the preload file after packaging the build. I get stuck here (notice that I did bump the version number to be sure it is your build):


image

**Review by flavioislima — APPROVED** [review]
It was a simple fix to make the preload to work now, everything works fine after that :D

**Pull request merged**
