### PR TITLE
[Tray Icon] Limit recent games on update

### PR DESCRIPTION
**Pull request by arielj**
This PR fixes the issue where the context menu of the tray icon was showing the full list of recent games instead of a limited amount.

Screenshot of the error:
image

I also added some tests for that and improved the setup of the test to mock less stuff.

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Review by redromnon — APPROVED** [review]
Tested. 
It does the job well :+1:

**Comment by redromnon** [comment]
I feel 5 is a sweet spot. 
Maybe we can add an option to change the number of recently played games to be shown? Do you think it's necessary?

**Comment by flavioislima** [comment]
> I feel 5 is a sweet spot. 
> Maybe we can add an option to change the number of recently played games to be shown? Do you think it's necessary?

We have this setting already. It goes from 1 to 10.

**Comment by redromnon** [comment]
> > I feel 5 is a sweet spot.
> > Maybe we can add an option to change the number of recently played games to be shown? Do you think it's necessary?
> 
> We have this setting already. It goes from 1 to 10.

I meant for the tray icon. Does the existing setting apply to the tray icon?

**Comment by arielj** [comment]
> > > I feel 5 is a sweet spot.
> > > Maybe we can add an option to change the number of recently played games to be shown? Do you think it's necessary?
> > 
> > 
> > We have this setting already. It goes from 1 to 10.
> 
> I meant for the tray icon. Does the existing setting apply to the tray icon?

yes, this PR is fixing that, it applies the same limit we have in the settings

**Review by flavioislima — APPROVED** [review]
Good stuff!

**Pull request merged**
