### PR TITLE
Display EGS free products popup on startup

### PR DESCRIPTION
**Pull request by flegald**
# Display EGS free products on startup
issue: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/305

Added feature to open new window to (regionally correct) Epic Game's free games of the week page.

New window is a popup handled exactly the same as the store link. 

```
    new BrowserWindow({ height: 700, width: 1200 }).loadURL(freeProductsUrl)
```

The IPC render action occurs once at start up, and is triggered in `App.tsx`

This new feature is toggle-able with a new General Setting ToggleSwitch which defaults to ON.

freetoggle

freegamespopup

### Bug Fix 
There was also a bug I noticed regarding the behavior of `setCheckForUpdatesOnStartup` toggle.
Even when checked into the `OFF` position using the toggle, the setting always reverted back to `ON` by itself.
This was because the following line would always resolve to true.
```
setCheckForUpdatesOnStartup(config.checkForUpdatesOnStartup || true)
```
I have replaced the `true` with `false`

My assumption is this was done to have the default value be `true`.

But this seems to be accomplished [here](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/electron/config.ts#L329)

-------------------------------------------------------------
Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [x] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [x] Created / Updated Tests (If necessary)
- [x] Created / Updated documentation (If necessary)

### CODE REVIEW

**Review by Nocccer — APPROVED** [review]
LGTM.

But i would love more a new tab "Free Games" like the "Store" tab instead of a popup on start.

**Comment by flegald** [comment]
> LGTM.
> 
> But i would love more a new tab "Free Games" like the "Store" tab instead of a popup on start.

Oh yeah for sure.

@flavioislima Do you have an opinion of this?

**Comment by Nocccer** [comment]
What about two other options:
1. Make the "Store" tab a dropdown list which shows, "Home" and "Free Games of the Week". 
2. Fetch the Free Games from the site and show them directly in heroic launcher. (Don't know if this is possible?)

**Comment by flegald** [comment]
I want to explore option 2. I originally thought it was not possible but I received an endpoint from CommandMC in Discord that may be able to do this. I agree it would be the nicest/classiest thing to do. I am going to edit this PR into WIP and see if we can get some integrated solution going.

**Comment by flegald** [comment]
Removing this PR as it is no longer current

**Pull request closed without merging**
