### PR TITLE
[Feat/Mac] Add Whisky Support

### PR DESCRIPTION
**Pull request by IsaacMarovitz**
This PR adds support for Whisky.

**TODO:**
- [ ] Add Whisky bottle detection
- [ ] Test test tset

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by blackxfiied** [comment]
will this be in the next release

**Comment by robertofd1995** [comment]
Why this got closed?

**Comment by alexandrius** [comment]
No idea why is this closed but, it's easy to trick HGC to rely on Whisky GPTK by running command below

```
cp ~/Library/Application\ Support/com.isaacmarovitz.Whisky/ ~/Library/Application\ Support/game-porting-toolkit.mac
```

**Comment by flavioislima** [comment]
> No idea why is this closed but, it's easy to trick HGC to rely on Whisky GPTK by running command below
> 
> ```
> cp ~/Library/Application\ Support/com.isaacmarovitz.Whisky/ ~/Library/Application\ Support/game-porting-toolkit.mac
> ```

Thanks I was actually about to start investigating how to do that. I will try it on heroic soon!

**Comment by flavioislima** [comment]
> @flavioislima Actually after digging some time I don't think we need GPTK anyway. The D3DMetal (aka GPTK) has already managed to get into Wine upstream

Are you sure? That would be huge. Any news about that that I can read?

**Comment by alexandrius** [comment]
@flavioislima haven't checked myself but according to @Gcenx , yes

**Comment by flavioislima** [comment]
> @flavioislima haven't checked myself but according to @Gcenx, yes
> https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/discussions/3119#discussioncomment-7226667

I think that supporting d3dmetal is different from shipping the libs with it. If we could that without apple suing us that would be cool for sure.

Afaik, it cannot be distributed with games, not sure what it says about software. Also if it could be downloaded afterwards without problems, that could be a solution as well. 🤔

Ideally I would like to find a way of heroic doing the whole gptk setup automatically on the background and having a toggle to enable disable it.

**Comment by flavioislima** [comment]
Thanks for clarifying. 


> I’ll confirm the Winehq package I’m providing as of wine-8.17 do indeed support Apples D3DMetal.
> 

But this means we don't need to download the apple package or compile the sources from brew? 

> 
> I _think_ I’d applied something to make this possible but I’ll need to review my custom sources later.

I appreciate if you find the logic to apply the libs unto a normal wine version so we could use the same logic here on Heroic. 😁

**Comment by alexandrius** [comment]
Ah I see now. 
All we gotta do to enable D3DMetal is run:

```
ditto /Volumes/Game\ Porting\ Toolkit-1.1/redist/lib /Applications/Wine\ Devel.app/Contents/Resources/wine/lib
```

**Comment by flavioislima** [comment]
> Ah I see now. 
> All we gotta do to enable D3DMetal is run:
> 
> ```
> ditto /Volumes/Game\ Porting\ Toolkit-1.1/redist/lib /Applications/Wine\ Devel.app/Contents/Resources/wine/lib
> ```

Yes, that was my first try and it did not work at least with the wine Heroic downloaded. I will try again with different versions.

I know it was not working because I tried a game that works with d3dmetal and doesn't work without it and also because of the overlay that was not showing the Rosetta info.

**Comment by alexandrius** [comment]
@flavioislima I don't think that would work with the wine version Heroic downloaded. You gotta install it with `brew`

```
brew install --cask --no-quarantine wine-devel
```

**Comment by flavioislima** [comment]
> @flavioislima I don't think that would work with the wine version Heroic downloaded. You gotta install it with `brew`
> 
> ```
> brew install --cask --no-quarantine wine-devel
> ```
> 
> Heroic downloads Wine Crossver by default, you gotta switch to `wine-staging` and also use correct path

Yeah, I really wanted to make this as simple as possible so just download heroic, download a game and heroic install latest wine crossover and spies the d3d libs to it.

**Comment by flavioislima** [comment]
Opened a new PR to add Whisky Support now if you guys want to test @IsaacMarovitz @alexandrius @robertofd1995 
#3358

**Pull request closed without merging**
