### PR TITLE
[Fix] Update Discord rich presence icon

### PR DESCRIPTION
**Pull request by TabulateJarl8**
Since the icon was updated in a recent release, I have added it as an asset in the Discord developer portal and updated the code in Heroic to reflect this new icon.

image

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [x] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [x] Created / Updated Tests (If necessary)
- [x] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by Etaash-mathamsetty** [comment]
haven't tested, but seems good to me

**Comment by Nocccer** [comment]
Can you add this maybe to my PR? So we don't have two PR for discord rich presence.

**Comment by TabulateJarl8** [comment]
How might I go about doing that? Should I just change the branch I'm merging into to be the branch your PR is on or should I do something else?

**Comment by Nocccer** [comment]
> How might I go about doing that? Should I just change the branch I'm merging into to be the branch your PR is on or should I do something else?

Sorry for the late reply. Just let it as it is. I already merged my PR.

**Review by Nocccer — APPROVED** [review]
Checked the icon name. LGTM. Thanks for that.

**Pull request merged**
