### PR TITLE
UI improvements and additions

### PR DESCRIPTION
**Pull request by 8Bitz0**
- Add blur effect on gamecard title.
- Add drop shadow on sidebar.
- Make colors fit together better.
- Disable user select on UI to remove accidental select when navigating.

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [x] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)

Screenshots:

hpr

### CODE REVIEW

**Comment by flavioislima** [comment]
Can you add screenshots?

**Comment by 8Bitz0** [comment]
> Can you add screenshots?

Okay, I added a screenshot.

**Review by flavioislima — APPROVED** [review]
Tested here, looks good!

**Comment by flavioislima** [comment]
Thanks for the contribution :D

**Pull request merged**
