### PR TITLE
os/darwin: Resized menu bar icons (tray icon) to 16x16 px.

### PR DESCRIPTION
**Pull request by syto203**
adjusted the size of the icon to 16x16 since on mojave it took a large area of the menu bar (grew to 512x512). don’t know if BigSur auto adjusts or not though.

Signed-off-by: syto203 <26351342+syto203@users.noreply.github.com>

### CODE REVIEW

**Comment by flavioislima** [comment]
can you attach screenshots of the before/after?

**Comment by syto203** [comment]
**Before:**
before-light
before-dark
**After:**
after-light
after-dark

**Review by flavioislima — APPROVED** [review]

**Review by entaromia — APPROVED** [review]
The icons are now displayed correctly on Big Sur, I missed that tray icons were not displayed while porting to mac, sorry.

**Comment by syto203** [comment]
ive also modified the app icon to this which can also be used in the tray.
heroic-icon

**Comment by adityaruplaha** [comment]
Merging after checks finish.

**Pull request merged**
