### PR TITLE
[UX] Simplify install dialog hiding wine settings by default. Warn about shared wine directory

### PR DESCRIPTION
**Pull request by arielj**
It's really common to see support requests of users that clicked the `Use Default Wine Settings` without understanding what it is for.

This PR aims to solve that with 2 things:
- the wine settings are hidden behind a checkbox (most users don't really need to touch those fields ever, the install dialog is simpler)
- then, if they check `Use Default Wine Settings` a warning is displayed to tell them to not use this option if they don't know what they are doing

Also, now when checking the `Use Default Wine Settings` option, the wine and prefix field are not hidden so users can see what that check box is doing (the fields are disabled so they don't change them).

image

image

image

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by imLinguin** [comment]
I think having a button instead of the checkbox makes more sense here. We are hiding that element when it's checked, so it doesn't need to be a checkbox

**Comment by arielj** [comment]
> I think having a button instead of the checkbox makes more sense here. We are hiding that element when it's checked, so it doesn't need to be a checkbox

right, I originally added it as a checkbox cause I was not hiding it, but then there were 2 checkboxes together and it looked weird

**Comment by arielj** [comment]
looks kinda weird with a button, I'm trying all the styles for buttons we have and it looks off, not sure exactly why

image

**Comment by flavioislima** [comment]
Can you make this button smaller or maybe use it like a link?
I think it is too big and calls too much attention on the dialog. Especially when installing games with a lot of DLCs, languages, etc.

Another idea would be to use a collapsible element, which may make more sense.

**Comment by arielj** [comment]
> Can you make this button smaller or maybe use it like a link? I think it is too big and calls too much attention on the dialog. Especially when installing games with a lot of DLCs, languages, etc.
> 
> Another idea would be to use a collapsible element, which may make more sense.

I tried making it smaller and it also looks odd (I didn't push any of that, the code in this PR is still the checkbox).

I can try with a details/summary element but I don't know if we have a style for that anywhere (I used it for the help component but it just the basic browser style, doesn't look great)

**Comment by arielj** [comment]
what about this with a details/summary element?

image
image

I think it looks better

**Review by flavioislima — APPROVED** [review]

**Pull request merged**
