### PR TITLE
[General] Show log output in Settings --> Log

### PR DESCRIPTION
**Pull request by Nocccer**
Because alot of user doesn't know how to run from a terminal or don't know where the logs are stored, i added a settings tab which shows the log output.

- Heroic logs are shown in the General Settings page.
  - Added buttons to choose between current and last log
  - Current log: image
  - Last log: image

- Legendary/Wine logs are shown in the Game Settings page.
  e.g.:
image

- Error and Warnings are highlighted with color (red, yellow)
- Added buttons to show current log file in folder or copy log content to clipboard
- Update material-ui to 5.3 (was renamed to mui)
- moved everything from logger in new folder logger

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [x] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by flavioislima** [comment]
Can the overflow be inside a fixed square with the log?
Perhaps add max-height, or a fixed height to it and then add overflow: auto.

**Comment by Nocccer** [comment]
@flavioislima already working on it. I don't get the scrollbar initial to the bottom. Not that importantn but would be cool if that would work somehow.

**Comment by Nocccer** [comment]
@flavioislima already working on it. I don't get the scrollbar initial to the bottom. Not that importantn but would be cool if that would work somehow.

**Comment by flavioislima** [comment]
This looks good but have you tried it on other platforms? at least on windows?

**Review by flavioislima — APPROVED** [review]
Ok, tested here, and looks good! :D

**Comment by Nocccer** [comment]
@flavioislima i did some quality of life changes and updated material-ui. If you havve time today to review we can release it with the hotfix, else release it later.

**Comment by flavioislima** [comment]
I think the icons to open folder and copy could be a transparent button. They do not seem to be aligned in the middle looking at the screenshots.
I think we have a class for transparent one, experiment a little.
Other than that looks good.

**Comment by Nocccer** [comment]
@flavioislima updated ui see pictures above

**Review by flavioislima — APPROVED** [review]

**Pull request merged**
