### PR TITLE
Keep installing if the pause/stop dialog is closed

### PR DESCRIPTION
**Pull request by Aikufurr**
Currently, the confirmation dialog for stopping a download will default to stopping the download and removing all files if the dialog is closed. Adding `cancelId: 0` will instead default to resuming the download.

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [X] Tested the feature and it's working on a current and clean install.
- [x] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Review by arielj — APPROVED** [review]
I tested this and it works as expected (closing the dialog with the ESC key works like clicking `Keep Installing`)

Also all buttons work as expected with this change too.

**Comment by flavioislima** [comment]
@Aikufurr can you provide more info on how to replicate this?

**Comment by Aikufurr** [comment]
@flavioislima So currently, if you start a download and then press the `PAUSE/CANCEL` button it brings up the dialog, if at that point you press `ESC` or close it via pressing the `X` the download is cancelled and doesn't save the files. With this commit, repeating those actions now continues the download instead of pausing/cancelling.

**Comment by flavioislima** [comment]
@Aikufurr thanks for fixing that 👍🏽

**Pull request merged**
