### PR TITLE
[UI] Installing text links to download manager

### PR DESCRIPTION
**Pull request by Etaash-mathamsetty**
Someone was requesting this on the heroic discord, so I decided to implement it

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [x] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by Etaash-mathamsetty** [comment]
Not sure how to fix this, could one of you help?

**Comment by Nocccer** [comment]
You need to import Link or you imported the wrong Link component.

**Comment by Etaash-mathamsetty** [comment]
> You need to import Link or you imported the wrong Link component.

Link was already used in other parts of this file

**Comment by flavioislima** [comment]
@Etaash-mathamsetty try updating your branch with `main` that should fix it.

i can see this branch is pretty outdated because the settings button does not go to the settings page anymore, it opens a modal and we changed this for a while already.

**Comment by Etaash-mathamsetty** [comment]
yeah I finally managed to reproduce it, thanks to the rebase and I fixed it.

**Review by flavioislima — APPROVED** [review]
LGTM

**Pull request merged**
