### PR TITLE
[Fix] Not Checking games update on all platforms on refresh

### PR DESCRIPTION
**Pull request by flavioislima**
Small fix that will check all games updates instead of only one platform when clicking the refresh button and on startup.

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [x] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by CommandMC** [comment]
Hm, maybe, instead of always ignoring the runner, we could refresh both libraries when on "All", and only the respective runner when on "Epic"/"Gog"

**Comment by flavioislima** [comment]
> Hm, maybe, instead of always ignoring the runner, we could refresh both libraries when on "All", and only the respective runner when on "Epic"/"Gog"

I just don't see a use case for that now since the libraries are unified. But ok, will do the change 👍🏽

**Review by CommandMC — APPROVED** [review]
IMO, when someone is filtering the library to only display Epic games, and then presses refresh, it should also only refresh their Epic games.
At least I'd imagine that's what the user expects

**Comment by flavioislima** [comment]
> IMO, when someone is filtering the library to only display Epic games, and then presses refresh, it should also only refresh their Epic games. At least I'd imagine that's what the user expects

Yes, you are right, I am not looking to the right place here. I just need to fix the list of updatable games we keep on the storage. That's the issue, don't need to touch the `refreshLibrary` method.

**Comment by flavioislima** [comment]
@CommandMC now I kept the old behavior and just fixed the list of games that were overridden when using a filter.

**Pull request merged**
