### PR TITLE
Add updates

### LINKED ISSUE #563: Automatically update the launcher in the background
**Is your feature request related to a problem? Please describe.**
Currently you need to download the .AppImage manually, It'd be nice to have auto updater functionality

**Describe the solution you'd like**
Every X minutes check whetever there are available updates (time can be customized). If there are updates, download them in the background. Then ask the user if he wants to restart Heroic, if he wants, restart & install. If not, ask him again in 10 minutes. 

Plus: Have a "Check updates" button that does this.

**Describe alternatives you've considered**
I've not considered alternatives.

**Note: It is possible to auto-update on Linux appimages, snaps, and flatpak (not sure about this last one) via electron builder's autoUpdater's "AppImageUpdater"**

See the snippet below:
```ts
import { NsisUpdater } from "electron-updater"
// Or MacUpdater, AppImageUpdater
```

https://www.electron.build/auto-update.html

### PR DESCRIPTION
**Pull request by dragonDScript**
Closes #563. See #563 for more information.

### Development

- [x] Fix TODO one: use a setting instead of fixed ten minutes.
- [x] Fix TODO two: possibility to disable updates.
- [x] Add to protocol
- [x] Fix some issues (see git commit history)
- [x] Add new settings to the UI
- [x] Fix coverage errors
- [x] Fix tests (again)

### Quality ensurance

- [ ] Try to update the app.
- [ ] Try to restart and see if changes were applied.
- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [x] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by dragonDScript** [comment]
Ready to review

**Comment by dragonDScript** [comment]
I'm stressing too much to fix these conflicts. Closing.

**Comment by flavioislima** [comment]
> I'm stressing too much to fix these conflicts. Closing. If someone else wants to take this PR or to remake all of my work, you're welcome.

Maybe start a new branch and port the code or cherry pick the commits. I'm not making any changes anymore to the code.

**Comment by dragonDScript** [comment]
> > I'm stressing too much to fix these conflicts. Closing. If someone else wants to take this PR or to remake all of my work, you're welcome.
> 
> Maybe start a new branch and port the code or cherry pick the commits. I'm not making any changes anymore to the code.

Ok I'm doing that

**Pull request closed without merging**
