### PR TITLE
[chore]: replace deprecated character which can lead to bug

### PR DESCRIPTION
**Pull request by 12ya**
replace deprecated character which can lead to bug

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [x] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [x] Created / Updated Tests (If necessary)
- [x] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by flavioislima** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/doc/cla.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by 12ya** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by arielj** [comment]
what do you mean by deprecated character? which bugs can it lead to?

**Comment by 12ya** [comment]
> what do you mean by deprecated character? which bugs can it lead to?

it seems like non-latin character was used, which can lead to "invisible unicode character" bug;
think it's good to change it just in case some people don't have  unicode highlighting

**Comment by arielj** [comment]
sorry I'm still not sure I understand what's the bug this is fixing, the en-dash character may not be a latin character but it's a valid character and it's different than the hypen character

I don't know if this is fixing a bug or a theoretical problem that some users may experience in their editor? how does the bug look like? what are the conditions for this bug to happen?

**Comment by CommandMC** [comment]
Closing this for now as I also don't see the value here. Feel free to re-open if there's an actual issue being resolved. As it stands right now, I would suspect that any moderately up-to-date Electron (which we're using) has no problem with this character

**Pull request closed without merging**
