### PR TITLE
Add Windowed Mode to Gamescope Options

### PR DESCRIPTION
**Pull request by MuraPura**
Adds a windowed mode to the upscaling options. Useful for really old games that open in a very tiny window due to low resolution.

image

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by flavioislima** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/doc/cla.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by MuraPura** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by arielj — COMMENTED** [review]
Shouldn't this configuration be used to add some flag for gamescope like it's done for the other options? https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/src/backend/launcher.ts#L200

or `Windowed` means no flag is passed? (I see that we currently pass either -f or -b but we have no option to not add one of those flags)

**Comment by MuraPura** [comment]
Gamescope by default is windowed. -f and -b are flags passed to change that default behavior. To my knowledge there isn't an explicit flag to pass for windowed since that is the default to begin with.

**Review by arielj — APPROVED** [review]

**Review by Etaash-mathamsetty — APPROVED** [review]

**Pull request merged**
