### PR TITLE
[Tech] update electron to 22.0.2

### PR DESCRIPTION
**Pull request by Etaash-mathamsetty**
yet another electron update 

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [x] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by flavioislima** [comment]
Can you add the change log for it when you open these PRs? So it is easier for us to review. 👍

**Comment by Etaash-mathamsetty** [comment]
https://github.com/electron/electron/releases/tag/v22.0.0

**Comment by flavioislima** [comment]
Ok but I think I will keep the current version on 2.5 and update Electron on the next major release. We had issues on Linux in the past by using the latest Electron version so we need to be more cautious and test in more distros.

**Comment by Etaash-mathamsetty** [comment]
> Ok but I think I will keep the current version on 2.5 and update Electron on the next major release. We had issues on Linux in the past by using the latest Electron version so we need to be more cautious and test in more distros.

yeah this was more targeted towards beta, it's just that I don't think work on the next beta has started

**Review by flavioislima — APPROVED** [review]

**Pull request merged**
