### PR TITLE
[i18n] Updated Translations

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Heroic Games Launcher/Login Page](https://hosted.weblate.org/projects/heroic-games-launcher/login-page/).

It also includes following components:

* [Heroic Games Launcher/GamePage](https://hosted.weblate.org/projects/heroic-games-launcher/gamepage/)

* [Heroic Games Launcher/Globals](https://hosted.weblate.org/projects/heroic-games-launcher/globals/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by flavioislima** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/doc/cla.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by J0anJosep** [comment]
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you all sign our [Contributor License Agreement](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/doc/cla.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below 

@flavioislima Is this enough? Thanks in 

I have read the CLA Document and I hereby sign the CLA

**Comment by flavioislima** [comment]
> > **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you all sign our [Contributor License Agreement](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/doc/cla.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below 
> 
> @flavioislima Is this enough? Thanks in advance
> 
> I have read the CLA Document and I hereby sign the CLA

You just need to paste the latest phrase as a comment for it to pass.

**Comment by flavioislima** [comment]
Ah ok, but this is a automated pr it does not need it.

**Comment by OriginalSimon** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by J0anJosep** [comment]
recheck

**Comment by Carmina16** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Drsheppard01** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Drsheppard01** [comment]
recheck

**Comment by DDinghoya** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by DDinghoya** [comment]
recheck

**Comment by CodeButter96** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by sxxeun09 — COMMENTED** [review]
I have read the CLA Document and I hereby sign the CLA

**Review by sxxeun09 — APPROVED** [review]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
