### PR TITLE
os/darwin: Mojave compatible Legendary binary

### PR DESCRIPTION
**Pull request by syto203**
This was compiled on Catalina to better support 10.14+.

Signed-off-by: syto203 <26351342+syto203@users.noreply.github.com>

### CODE REVIEW

**Comment by adityaruplaha** [comment]
Can someone on Mac please test this? Then this can be merged.

**Comment by flavioislima** [comment]
@syto203 can you open a PR with your changes on the legendary project? would be nice for them to take a look if possible. And also provide your repo with the changes.

thanks!

**Comment by syto203** [comment]
nothing was changed from legendary. 
Building with github actions or on a mac with Big Sur will use a version with python not compatible with Catalina or Mojave as a result a pyinstaller package will not work.

**Comment by flavioislima** [comment]
@entaromia can you test this one when you have time? 👍🏽

**Comment by entaromia** [comment]
> @entaromia can you test this one when you have time? 👍🏽 

Yes, i will test it in few hours.

**Review by entaromia — APPROVED** [review]
Works as same as before on Big Sur.

**Comment by adityaruplaha** [comment]
Merging after checks finish.

**Review by adityaruplaha — APPROVED** [review]

**Comment by flavioislima** [comment]
@syto203 Can you help us regarding this issue: #642 ?
Since you have compiled the binary before and it was working, can you compile it again for us to test? because the one I did is working only on Intel Macs with Catalina. The one you did was working fine on all versions and also on M1 Macs.

Thanks!

**Comment by syto203** [comment]
Yeah sure I’ll do it as soon as possible.
Did you build it on an actual machine or a VM?

**Comment by flavioislima** [comment]
> Yeah sure I’ll do it as soon as possible.
> Did you build it on an actual machine or a VM?

I did it on a real machine. But with intel, a MacBook pro 2019.

**Comment by syto203** [comment]
hmm. i was on a VM.

**Comment by syto203** [comment]
check this one syto203@7bcfa1b
it should support Apple Silicon

**Pull request merged**
