### PR TITLE
[General/Hotfix] Fix gog games not launching via protocol

### PR DESCRIPTION
**Pull request by Nocccer**
This fixes starting of gog games via protocol. 
After the beta becomes stable, we will take @CommandMC refactor of protocol (https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/1602)

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Review by CommandMC — APPROVED** [review]
I guess this works for now

Although I'm already dreading the merge conflicts my PR will have by then. Oh well, that's future me's problem

**Comment by Nocccer** [comment]
> I guess this works for now
> 
> Although I'm already dreading the merge conflicts my PR will have by then. Oh well, that's future me's problem

I had many conflicts with the none-steam pr. But fast merges of heavy refactors is not a good idea before a stable release.

**Comment by flavioislima** [comment]
> > > I guess this works for now
> > > Although I'm already dreading the merge conflicts my PR will have by then. Oh well, that's future me's problem
> > 
> > 
> > I had many conflicts with the none-steam pr. But fast merges of heavy refactors is not a good idea before a stable release.
> 
> we could just make a pre-release (or beta 3) or something and make sure it's stable before releasing stable

No, the beta is running for too long now. we won't have another beta for this version. we can start a new beta after we release 2.4 for v2.5 then we can do further refactors.

**Comment by flavioislima** [comment]
It is working fine when installed with pacman on Arch.
On flatpak it launches heroic but no game works, neither gog or epic

**Comment by Nocccer** [comment]
> It is working fine when installed with pacman on Arch. On flatpak it launches heroic but no game works, neither gog or epic

For me it worked. Maybe the game didn't launch because of a launch error? Did you checked if it works running directly from heroic?

**Comment by flavioislima** [comment]
> > It is working fine when installed with pacman on Arch. On flatpak it launches heroic but no game works, neither gog or epic
> 
> For me it worked. Maybe the game didn't launch because of a launch error? Did you checked if it works running directly from heroic?

Yes probably. So its good to merge.

**Pull request merged**
