### PR TITLE
[UI] Improve styling in various areas

### PR DESCRIPTION
**Pull request by Etaash-mathamsetty**
these are just some minor styling improvements (kind of major now actually)

1. moved game not available text to the right side so that the game title is now readable and made the text fit into one line
image
2. login manager now looks correct on all themes, and added a small amount of opacity for looks (this was a theme that looked broken originally)
image

3. reverted changes to the zombie theme (made in #1822), since they are no longer needed

4. remove the gradient in the title's background when you hover over the gamecard and see the title

5. resize the arrow in the back to top button with the button

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [x] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by Etaash-mathamsetty** [comment]
bumping this so someone can review it

**Comment by arielj** [comment]
hey @Etaash-mathamsetty when making these kind of changes, can you show the before and after of each change? it's hard to know what is the specific issue this is addressing to test it and in some cases like scaling the arrow or removing a gradient is not clear why that those things were a problem in the first place (without a specific problem it's not clear if a change fixes an actual issue or a style preference)

**Comment by Etaash-mathamsetty** [comment]
> hey @Etaash-mathamsetty when making these kind of changes, can you show the before and after of each change? it's hard to know what is the specific issue this is addressing to test it and in some cases like scaling the arrow or removing a gradient is not clear why that those things were a problem in the first place (without a specific problem it's not clear if a change fixes an actual issue or a style preference)

Will do once I reach home

**Comment by Etaash-mathamsetty** [comment]
before:
image
image
image
(simulating high resolution display):
image

after:
image
image
image
(simulating a high resolution display):
image

**Review by flavioislima — APPROVED** [review]
Looks good 👍🏽

**Pull request merged**
