### PR TITLE
[Flatpak] Update manifest for UMU support

### PR DESCRIPTION
**Pull request by R1kaB3rN**
Related to https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3480 and depends on the updated Flatpak support in ULWGL aka umu to be merged/reviewed. After the Flatpak umu is installed in the user's system, the Heroic Games Launcher will need to allow explicit access to umu's `$XDG_DATA_HOME/umu` and the system `/app/share` directory to run games through the launcher. 

The reason is because, without going into the details, umu will currently copy files from `/app/share` to its private Flatpak directory, and Valve's Steam Runtime tools (e.g., Pressure Vessel) are designed to only be executed from the user's home directory. Without explicit visibility to these directories defined in Heroic's manifest, it's likely that umu will fail to launch games successfully due to Flatpak's strict filesystem permissions.

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by flavioislima** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/doc/cla.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by R1kaB3rN** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by GloriousEggroll** [comment]
umu flatpak update has been merged:
https://github.com/Open-Wine-Components/umu-launcher/pull/82

However please note this PR needs modification now as the umu-launcher manifest has been renamed from:

org.openwinecomponents.umu.launcher

to:

org.openwinecomponents.umu.umu-launcher

**Comment by flavioislima** [comment]
> umu flatpak update has been merged: [Open-Wine-Components/umu-launcher#82](https://github.com/Open-Wine-Components/umu-launcher/pull/82)
> 
> However please note this PR needs modification now as the umu-launcher manifest has been renamed from:
> 
> org.openwinecomponents.umu.launcher
> 
> to:
> 
> org.openwinecomponents.umu.umu-launcher

Thanks for the letting us know 👍🏽

**Comment by CommandMC** [comment]
*I don't think* the manifest kept in this repo is that relevant? It's only used when installing a local test build.
I've opened https://github.com/flathub/com.heroicgameslauncher.hgl/pull/153 to add these changes to the Flathub manifest

**Review by flavioislima — APPROVED** [review]

**Pull request merged**
