### PR TITLE
[UI] Fix downloads styling

### PR DESCRIPTION
**Pull request by Etaash-mathamsetty**
There were these white borders around all the items in downloads view, I changed a small thing in the CSS so that now it's not an ugly white :D

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [x] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by Etaash-mathamsetty** [comment]
whoops this is not meant for main

**Comment by flavioislima** [comment]
@Etaash-mathamsetty can you add screenshots with before and after?

**Comment by flavioislima** [comment]
I tested here and I think it is even better if we use this color for the background like this:
image

**Comment by flavioislima** [comment]
maybe also remove the border of the last element

**Comment by Etaash-mathamsetty** [comment]
> maybe also remove the border of the last element

wdym by this?

**Comment by flavioislima** [comment]
> > maybe also remove the border of the last element
> 
> wdym by this?

Can you see that the last game on the list has a line at the bottom? It is ugly, we should have a line to divide the items when having more than one, but the last one should not have imo.
So you can create a css rule to remove the border from last item.

**Comment by Etaash-mathamsetty** [comment]
> > > maybe also remove the border of the last element
> > 
> > 
> > wdym by this?
> 
> Can you see that the last game on the list has a line at the bottom? It is ugly, we should have a line to divide the items when having more than one, but the last one should not have imo. So you can create a css rule to remove the border from last item.

I think I came up with a simpler solution than that, I switched to use border-top, which just removes the bottom border

**Comment by flavioislima** [comment]
> > > > maybe also remove the border of the last element
> > > 
> > > 
> > > wdym by this?
> > 
> > 
> > Can you see that the last game on the list has a line at the bottom? It is ugly, we should have a line to divide the items when having more than one, but the last one should not have imo. So you can create a css rule to remove the border from last item.
> 
> I think I came up with a simpler solution than that, I switched to border-top, which just removes the bottom border, the next element's top border will become the bottom border for the previous element

You are pretty smart, that works as well 🤣

**Review by flavioislima — APPROVED** [review]
Looks cool now 👍🏽

**Pull request merged**
