### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by CosmicFusion**
<--- Put the description here --->
Fixed EAC Info , as it now works in linux but needs to  be enabled the the game dev.
---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [x] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by wiryfuture** [comment]
Not quite as simple as that, they need to enable Epic Online Services too (afaik) which is a different sdk lol.
Imo something along the lines of "Online supported on most titles" or smth

**Comment by CosmicFusion** [comment]
> Not quite as simple as that, they need to enable Epic Online Services too (afaik) which is a different sdk lol.
> Imo something along the lines of "Online supported on most titles" or smth

This issue was solved  , now you just drop a binary in your "EAC" library directory.
As stated in : 
https://steamcommunity.com/groups/steamworks/announcements/detail/3137321254689909034

**Comment by wiryfuture** [comment]
> > Not quite as simple as that, they need to enable Epic Online Services too (afaik) which is a different sdk lol.
> > Imo something along the lines of "Online supported on most titles" or smth
> 
> This issue was solved , now you just drop a binary in your "EAC" library directory. As stated in : https://steamcommunity.com/groups/steamworks/announcements/detail/3137321254689909034
> 
> 

Heroic itself doesn't do this though so saying we do would just be lying 😆

**Comment by CosmicFusion** [comment]
> > > Not quite as simple as that, they need to enable Epic Online Services too (afaik) which is a different sdk lol.
> > > Imo something along the lines of "Online supported on most titles" or smth
> > 
> > This issue was solved , now you just drop a binary in your "EAC" library directory. As stated in : https://steamcommunity.com/groups/steamworks/announcements/detail/3137321254689909034
> > 
> > 
> 
> Heroic itself doesn't do this though so saying we do would just be lying 😆 

I mean I said the game dev has to not heroic , but understandable

**Pull request closed without merging**
