### PR TITLE
Support nagivating Heroic using a gamepad

### PR DESCRIPTION
**Pull request by arielj**
This PR adds support to control Heroic using a gamepad.

Implemented:
- using the Gamepad API
- invoke methods on electron to simulate key presses and wheel
- navigate the app using pad or left stick
- scroll the main window using right stick
- repeat actions when holding a button/stick
- trigger a `click` on the currently focused element when pressing A in an Xbox controller
- Xbox, PS3, PS5 and Gamecub layouts
- interacting with select tags
- virtual keyboard

TODO:
- ~~try other controllers (I only have an Xbox controller to test this)~~
- ~~I cannot find a way to trigger the dropdown for `select` tags (tried with the `click()` method, simulating a `Return` key press and simulating a `mouseDown` event with electron), maybe we need to display a custom dropdown when using a gamepad~~

Ideas to improve this for the futre (I'd say to leave them for another PR as V2 of this feature):
- ~~for the search field to work we'll need a virtual keyboard~~
- let the user re-assign controller buttons (decide which stick scrolls, pick what to do with each button, etc)
- let the user configure the scroll sensitivity
- let the user configure the repeat speed

Closes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/107

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Review by flavioislima — APPROVED** [review]
Amazing Job, man!
tested here and I was able to navigate nicely.
I was able to install, configure and play a game.
Ofc some things are not controllable since we are using some dialogs from the system but I think this is fine.
I have plans to create our own dialog screens, at least to replace the `showErrorBox` and `showMessageBox` from electron, so if a game has update, the user can use the controller to skip the update, currently this is not possible.
But lets improve all of this in the future!

**Comment by veganjin** [comment]
im sorry im new to git and heroic but i havent been able to get my ps3 controller to get detected in wwz aftermath… online works gladly tho im curious if you have any advice on this? if i load the game with steam then controller works but of course it doesnt get online…. thank you for all your hard work this is amazing

**Comment by arielj** [comment]
hey @veganjin, I think you are probably refering to something different to what this feature is about, since you talk about the controller when running a game in steam.

This pull request is about using your controller to control the Heroic application (like browsing the game library, pick a game an run it), it is NOT related to the controller being recognized by games since that part is not handled by Heroic (but by wine/proton).

Also, for this particular feature (the gamepad to navigate heroic) you need to use the code from github (the latest realese didn't include this). If this is what you really mean, check if your gamepad is detected here https://gamepad-tester.com usign a chromium-based browser (chrome, chromium, opera, brave, edge, don't try firefox or safari for example)? if so, can you share the information that site shows? you should have a device name and a bit more info

If you mean the ps3 controller is not recorgnized by a game, I'd say to join the discord and ask there, I know some people have that same controller and can maybe help you.

**Comment by veganjin** [comment]
oh awesome! yes i did check the gamepad website and it was detected
immediately…. i wasnt aware of the discord so ill check it out…. i wonder
if its not just a little something to add to the launch command:… thank yo
very much Ariel!

**Comment by veganjin** [comment]
Sony PS3 Dualshock054c-0268-Sony PLAYSTATION(R)3 Controller
INDEX
0
CONNECTED
Yes
MAPPING
n/a
TIMESTAMP
123441.00000
Pose
n/a
HapticActuators
n/a
Hand
n/a
DisplayId
n/a
Vibration
n/a
B0
0.00
B1
0.00
B2
0.00
B3
0.00
B4
0.00
B5
0.00
B6
0.00
B7
0.00
B8
0.00
B9
0.00
B10
0.00
B11
0.00
B12
0.00
B13
0.00
B14
0.00
B15
0.00
B16
0.00
AXIS 0
0.00000
AXIS 1
0.00000
AXIS 2
-1.00000
AXIS 3
0.00000
AXIS 4
0.00000
AXIS 5
-1.00000

**Pull request merged**
