### PR TITLE
[Fix] Fix some bugs with the OSK

### PR DESCRIPTION
**Pull request by Etaash-mathamsetty**
The OSK has some minor CSS problems, so this PR fixes them
it also fixes a minor bug from my previous PR regarding the OSK (oops)

- [x] Tested the feature and it's working on a current and clean install.
- [x] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by Etaash-mathamsetty** [comment]
the macOS tests keep failing cuz of that internet issue, and it's always only macOS, strange

**Comment by arielj** [comment]
Oops I actually included a similar fix in https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/1641 the other day

**Comment by Etaash-mathamsetty** [comment]
> Oops I actually included a similar fix in #1641 the other day
so either you change the mapping to be Y for space and X for backspace, and I only change minor css stuff in this
or you can delete the modification
X for space and Y for backspace is going to confuse the living daylight out of me lol

**Comment by arielj** [comment]
Maybe we can check in the UX/UI channel what people expect for the buttons, the button for backspace was already coded in the Y since the beginning of this feature so changing that might confuse people already used to it.

But I don't know if there's an expectation from users, at some point I remember adding the different functions for each button based on feedback in discord, but there was no feature before so maybe people prefer Y for space now after using this for a while. I don't know, I certainly don't want to just change this without asking the users.

**Comment by Etaash-mathamsetty** [comment]
> Maybe we can check in the UX/UI channel what people expect for the buttons, the button for backspace was already coded in the Y since the beginning of this feature so changing that might confuse people already used to it.
> 
> But I don't know if there's an expectation from users, at some point I remember adding the different functions for each button based on feedback in discord, but there was no feature before so maybe people prefer Y for space now after using this for a while. I don't know, I certainly don't want to just change this without asking the users.
> 
> I wonder how that works in the steam deck, like in the on screen keyboard of steam in the steamdeck, I think trying to replicate that would be the best since in desktop not everyone uses the game controller to navigate the UI but in the deck most user will and it would be nice to keep the same behavior as the native osk.

Why don't we just ask them on discord or something
I will try the steam deck UI on pc and see what they use
I am personally used to this layout when typing stuff on my Xbox, so that's why I suggested a change
We could also put it behind a toggle

**Comment by arielj** [comment]
> > Maybe we can check in the UX/UI channel what people expect for the buttons, the button for backspace was already coded in the Y since the beginning of this feature so changing that might confuse people already used to it.
> > But I don't know if there's an expectation from users, at some point I remember adding the different functions for each button based on feedback in discord, but there was no feature before so maybe people prefer Y for space now after using this for a while. I don't know, I certainly don't want to just change this without asking the users.
> > I wonder how that works in the steam deck, like in the on screen keyboard of steam in the steamdeck, I think trying to replicate that would be the best since in desktop not everyone uses the game controller to navigate the UI but in the deck most user will and it would be nice to keep the same behavior as the native osk.
> 
> Why don't we just ask them on discord or something I will try the steam deck UI on pc and see what they use I am personally used to this layout (the one in this pr) when typing stuff on my Xbox, so that's why I suggested a change We could also put it behind a toggle, so by default we set x to space and y to backspace and with the toggle on, y for space and x for backspace

Yes, I think it can be asked in discord.

I understand that some UIs like xbox work in some way but maybe other users expect it to work differently because they are used to something different (I don't remember how was the discussion when I implemented this originally, the steam deck wasn't even released back then to check)

I'm ok changing that if people are or with the change, I don't want to change it without knowing what more users expect (I'm not an xbox user so for me anything works, I'm used to the current config because it's the only one I know)

Ideally I would want a `controller` setting to let users map any button to the different actions we can do instead of adding one specific toggle for this particular buttons pair (like... why would we have a toggle for the X/Y in the virtual keyboard and not a toggle for buttons in other places?). That way if somebody wants... I don't know... R to acts as backspace, they set that and everyone's happy haha. I just didn't have the time to code that.

**Comment by Etaash-mathamsetty** [comment]
> > > Maybe we can check in the UX/UI channel what people expect for the buttons, the button for backspace was already coded in the Y since the beginning of this feature so changing that might confuse people already used to it.
> > > But I don't know if there's an expectation from users, at some point I remember adding the different functions for each button based on feedback in discord, but there was no feature before so maybe people prefer Y for space now after using this for a while. I don't know, I certainly don't want to just change this without asking the users.
> > > I wonder how that works in the steam deck, like in the on screen keyboard of steam in the steamdeck, I think trying to replicate that would be the best since in desktop not everyone uses the game controller to navigate the UI but in the deck most user will and it would be nice to keep the same behavior as the native osk.
> > 
> > 
> > Why don't we just ask them on discord or something I will try the steam deck UI on pc and see what they use I am personally used to this layout (the one in this pr) when typing stuff on my Xbox, so that's why I suggested a change We could also put it behind a toggle, so by default we set x to space and y to backspace and with the toggle on, y for space and x for backspace
> 
> Yes, I think it can be asked in discord.
> 
> I understand that some UIs like xbox work in some way but maybe other users expect it to work differently because they are used to something different (I don't remember how was the discussion when I implemented this originally, the steam deck wasn't even released back then to check)
> 
> I'm ok changing that if people are or with the change, I don't want to change it without knowing what more users expect (I'm not an xbox user so for me anything works, I'm used to the current config because it's the only one I know)
> 
> Ideally I would want a `controller` setting to let users map any button to the different actions we can do instead of adding one specific toggle for this particular buttons pair (like... why would we have a toggle for the X/Y in the virtual keyboard and not a toggle for buttons in other places?). That way if somebody wants... I don't know... R to acts as backspace, they set that and everyone's happy haha. I just didn't have the time to code that.

lol on the steam deck, Y is used for space and X is used for backspace, I guess everyone follows a similar convention?
proof:
image

**Comment by arielj** [comment]
> > > > Maybe we can check in the UX/UI channel what people expect for the buttons, the button for backspace was already coded in the Y since the beginning of this feature so changing that might confuse people already used to it.
> > > > But I don't know if there's an expectation from users, at some point I remember adding the different functions for each button based on feedback in discord, but there was no feature before so maybe people prefer Y for space now after using this for a while. I don't know, I certainly don't want to just change this without asking the users.
> > > > I wonder how that works in the steam deck, like in the on screen keyboard of steam in the steamdeck, I think trying to replicate that would be the best since in desktop not everyone uses the game controller to navigate the UI but in the deck most user will and it would be nice to keep the same behavior as the native osk.
> > > 
> > > 
> > > Why don't we just ask them on discord or something I will try the steam deck UI on pc and see what they use I am personally used to this layout (the one in this pr) when typing stuff on my Xbox, so that's why I suggested a change We could also put it behind a toggle, so by default we set x to space and y to backspace and with the toggle on, y for space and x for backspace
> > 
> > 
> > Yes, I think it can be asked in discord.
> > I understand that some UIs like xbox work in some way but maybe other users expect it to work differently because they are used to something different (I don't remember how was the discussion when I implemented this originally, the steam deck wasn't even released back then to check)
> > I'm ok changing that if people are or with the change, I don't want to change it without knowing what more users expect (I'm not an xbox user so for me anything works, I'm used to the current config because it's the only one I know)
> > Ideally I would want a `controller` setting to let users map any button to the different actions we can do instead of adding one specific toggle for this particular buttons pair (like... why would we have a toggle for the X/Y in the virtual keyboard and not a toggle for buttons in other places?). That way if somebody wants... I don't know... R to acts as backspace, they set that and everyone's happy haha. I just didn't have the time to code that.
> 
> lol on the steam deck, Y is used for space and X is used for backspace, I guess everyone follows a similar convention? proof: image

good, ok I think we can go with Y/Triangle for space and X/Square for backspace if steam deck uses that, maybe I can apply this changes to my PR with the controller hints since I'll need to change the hints for this too

**Comment by Etaash-mathamsetty** [comment]
> > > > > Maybe we can check in the UX/UI channel what people expect for the buttons, the button for backspace was already coded in the Y since the beginning of this feature so changing that might confuse people already used to it.
> > > > > But I don't know if there's an expectation from users, at some point I remember adding the different functions for each button based on feedback in discord, but there was no feature before so maybe people prefer Y for space now after using this for a while. I don't know, I certainly don't want to just change this without asking the users.
> > > > > I wonder how that works in the steam deck, like in the on screen keyboard of steam in the steamdeck, I think trying to replicate that would be the best since in desktop not everyone uses the game controller to navigate the UI but in the deck most user will and it would be nice to keep the same behavior as the native osk.
> > > > 
> > > > 
> > > > Why don't we just ask them on discord or something I will try the steam deck UI on pc and see what they use I am personally used to this layout (the one in this pr) when typing stuff on my Xbox, so that's why I suggested a change We could also put it behind a toggle, so by default we set x to space and y to backspace and with the toggle on, y for space and x for backspace
> > > 
> > > 
> > > Yes, I think it can be asked in discord.
> > > I understand that some UIs like xbox work in some way but maybe other users expect it to work differently because they are used to something different (I don't remember how was the discussion when I implemented this originally, the steam deck wasn't even released back then to check)
> > > I'm ok changing that if people are or with the change, I don't want to change it without knowing what more users expect (I'm not an xbox user so for me anything works, I'm used to the current config because it's the only one I know)
> > > Ideally I would want a `controller` setting to let users map any button to the different actions we can do instead of adding one specific toggle for this particular buttons pair (like... why would we have a toggle for the X/Y in the virtual keyboard and not a toggle for buttons in other places?). That way if somebody wants... I don't know... R to acts as backspace, they set that and everyone's happy haha. I just didn't have the time to code that.
> > 
> > 
> > lol on the steam deck, Y is used for space and X is used for backspace, I guess everyone follows a similar convention? proof: image
> 
> good, ok I think we can go with Y/Triangle for space and X/Square for backspace if steam deck uses that, maybe I can apply this changes to my PR with the controller hints since I'll need to change the hints for this too

So should I revert them from here?

**Comment by flavioislima** [comment]
@arielj do you want to double test this? can we merge it?

**Review by arielj — APPROVED** [review]

**Comment by arielj** [comment]
Sorry I forgot about this, I've been too busy lately haha, merging this.

**Pull request merged**
