### PR TITLE
[GOG]: don't check for notInstallable during library sync

### PR DESCRIPTION
**Pull request by imLinguin**
This should resolve number of issues, but also allow players with pre-release access to actually download their games.

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Review by arielj — APPROVED** [review]
looks good to me, I can't confirm the solution cause I never had the issue if games flagged as not installable in the first place

**Comment by imLinguin** [comment]
There is one flaw with this approach. Demos are treated as full releases because the endpoint we use collects different game editions under one entry.

**Review by flavioislima — APPROVED** [review]
lgtm but I have no way of testing it

**Comment by daygr** [comment]
I was experiencing this problem, I used the AppImage from this run https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/8850391069 and that fixed the issue for me. I shared my logs from 2.14.1 on a [discord thread](https://discord.com/channels/812703221789097985/1207885396382580846), and they are now correct and do not show any timeouts or other errors.

**Pull request merged**
