### PR TITLE
[UI] Custom Error Dialog

### PR DESCRIPTION
**Pull request by Nocccer**
- Replaced electron `dialog.showErrorBox` with custom error dialog in frontend.
- Adapt `showErrorBoxModalAuto` to send error to custom error dialog

image

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by flavioislima** [comment]
@Nocccer 
Does this also cover the dialogs that we talked about on #1152 ?
I mean the other dialogs like the one for uninstall, to skip update, etc?

**Comment by Nocccer** [comment]
> @Nocccer Does this also cover the dialogs that we talked about on #1152 ? I mean the other dialogs like the one for uninstall, to skip update, etc?

For now it only covers the error dialogs. So all other dialogs are still the old once.

**Comment by flavioislima** [comment]
OK. So then lets keep the issue opened so we know that we need to fix the other dialogs as well 👍🏽

**Review by flavioislima — APPROVED** [review]
LGTM 👍🏽

**Pull request merged**
