### PR TITLE
Catalan translation (99%)

### PR DESCRIPTION
**Pull request by dragonDScript**
Added catalan translation

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Created / Updated Tests
- [ ] Created / Updated documentation

Tested on a Clean Install with AppImage:
- [ ] Login
- [ ] Download a Game
- [ ] Import a Game
- [ ] Launch Default config
- [ ] Launch Personalized Config
- [ ] Launch wine
- [ ] Launch Proton
- [ ] Launch Custom Proton
- [ ] Launch Tools (Winetricks and Winecfg)
- [ ] Uninstall Game
- [ ] Move Game
- [x] Languages (Test if no translation stopped working)

### CODE REVIEW

**Comment by dragonDScript** [comment]
That CI fail doesn't look like it's my fault

**Comment by flavioislima** [comment]
> 
> 
> That CI fail doesn't look like it's my fault

What are you doing? we do not translate JSON files anymore. we need to use Weblate :P

**Comment by dragonDScript** [comment]
> > That CI fail doesn't look like it's my fault
> 
> What are you doing? we do not translate JSON files anymore. we need to use Weblate :P

wtf ok

**Comment by flavioislima** [comment]
> 
> 
> > > That CI fail doesn't look like it's my fault
> > 
> > 
> > What are you doing? we do not translate JSON files anymore. we need to use Weblate :P
> 
> wtf ok, we should clarify that in the docs

but it is. quite big to be honest

**Comment by flavioislima** [comment]
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Translations

**Pull request closed without merging**
