### PR TITLE
[Fix] error when gamesdb returns 404

### PR DESCRIPTION
**Pull request by imLinguin**
Should fix errors with Cyberpunk 2077 Goodies, and other products that return 404 from gamesdb endpoint

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [x] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Review by flavioislima — APPROVED** [review]

**Comment by Oaklight** [comment]
some games still returns 404:
- Hundred Days - Winemaking Simulator
- The Lion's Song

**Comment by imLinguin** [comment]
Well, that's expected in some cases. However at this moment it should fallback to data from GOG API if available

**Comment by Oaklight** [comment]
Why GOG? I should be more specific. These are Epic games

**Comment by imLinguin** [comment]
Could you post the log proving that? GamesDB is only used for GOG at this moment

**Comment by Oaklight** [comment]
Oh, I see. Should I create another issue then? I only meant to report 404 issue for some of my Epic games when I tried to go to their Epic store page in the Tool page. This is the only 404-related open issue page I found so...

**Comment by imLinguin** [comment]
Separate issue would be great. If it's causing serious issues then create one

**Comment by Oaklight** [comment]
so far I was able to run them without error. The issue now is just the 404 webpage from Tool page, while I can search and view directly from the Store page.

**Comment by imLinguin** [comment]
Then it's a different type of 404 than was improved on this PR

**Pull request merged**
