### PR TITLE
Add important warning about wine dependencies to readme description

### PR DESCRIPTION
**Pull request by makzef**
README does not provide clear description of how to install and use wine with Heroic for casual users. 

When I first tried to use HGL, I faced the problem that wine installation is not working to launch games. I tried several time to reinstall HGL and different games. This led me to join the discord channel and ask for support. I found out in the topic of *Frequently Asked Questions* (with the help from channel members) that wine dependencies should be installed.

This simple warning in description should save time for casual users, who don't have deep knowledge of wine. Also they won't bother other people with issues that are obviously easy to fix (like in my case described above).

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by flavioislima** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/doc/cla.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by makzef** [comment]
recheck

**Comment by flavioislima** [comment]
> recheck

you need to write a comment with that same phrase for it to work:
`I have read the CLA Document and I hereby sign the CLA`

**Comment by makzef** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by makzef** [comment]
recheck

**Comment by CommandMC** [comment]
I do somewhat doubt that casual users are going to see this, but it doesn't hurt to have

**Review by flavioislima — APPROVED** [review]
Thanks for the contribution

**Pull request merged**
