### PR TITLE
[i18n] Updated Translations

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Heroic Games Launcher/Login Page](https://hosted.weblate.org/projects/heroic-games-launcher/login-page/).

It also includes following components:

* [Heroic Games Launcher/GamePage](https://hosted.weblate.org/projects/heroic-games-launcher/gamepage/)

* [Heroic Games Launcher/Globals](https://hosted.weblate.org/projects/heroic-games-launcher/globals/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by flavioislima** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/doc/cla.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by dziugas1959** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by draaurkh** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by draaurkh** [comment]
recheck

**Comment by manurtinez** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by manurtinez** [comment]
recheck

**Comment by Kefir2105** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Kefir2105** [comment]
recheck

**Comment by bittin** [comment]
i been pretty busy last week and are very busy this week too, so i won't have time to watch the CLA until at earliest next week
please don't delay the release on this

**Comment by SirenTheSiren** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by SirenTheSiren** [comment]
recheck

**Comment by bittin** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by bittin** [comment]
@flavioislima saw that you added me now, so Swedish can be pushed in again by next push

**Comment by Periyte** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Periyte** [comment]
recheck

**Comment by omuratlihan** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by omuratlihan** [comment]
recheck

**Comment by bittin** [comment]
recheck

**Pull request merged**
