### PR TITLE
[FIX] Wine Stuck sometimes at adding registry key

### PR DESCRIPTION
**Pull request by K900**
Otherwise, newer Wine versions will prompt to overwrite it and loop there forever.

<--- Put the description here --->

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [x] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by arielj** [comment]
can you explain the problem better? how can this be reproduced?

**Comment by K900** [comment]
I'm not entirely sure _how_ it can be reproduced - it happens consistently on some of my Wine prefixes, but basically, the `reg add` command will just get stuck. `strace`ing it shows it gets stuck on an "overwrite? [yes/no]" prompt, which can be bypassed with `/f`.

**Comment by Etaash-mathamsetty** [comment]
> I'm not entirely sure _how_ it can be reproduced - it happens consistently on some of my existing Wine prefixes, but not new ones. Basically, the `reg add` command will just get stuck. `strace`ing it shows it gets stuck on an "overwrite? [yes/no]" prompt, which can be bypassed with `/f`.

that means that the registry key is already there, which is a strange, but I don't see any problem with adding a /f here

**Review by Etaash-mathamsetty — APPROVED** [review]

**Comment by K900** [comment]
Not really sure why the CI failed here, but seems unrelated?

**Pull request merged**
