### PR TITLE
[Sideload] browser, add support for DRM

### PR DESCRIPTION
**Pull request by imLinguin**
This switches our electron to https://github.com/castlabs/electron-releases  
Heroic will now pull Widevine CRM module on startup, and check for updates on each startup. 

I already tested Crunchyroll and Prime Video, both worked as expected

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by imLinguin** [comment]
I somehow missed #2760. Closing this

**Comment by imLinguin** [comment]
Okay since 2760 is now closed I'm reopening this....

**Comment by flavioislima** [comment]
My tests:
macOS:
- HBO Max ❌
- Prime Video ❌
- CrunchyRoll❌
- AppleTV ✅

SteamDeck:
- HBO Max❌
- PrimeVideo ✅
- Crunchyroll ✅
- AppleTV

**Comment by flavioislima** [comment]
Changing userAgent does not help.

**Comment by imLinguin** [comment]
We'll try to use https://github.com/castlabs/electron-releases/wiki/EVS  
like we discussed on Discord

**Pull request merged**
