### PR TITLE
[Exp]: ULWGL support

### PR DESCRIPTION
**Pull request by imLinguin**
Experimental feature with ULWGL support. The feature is enabled by default.

Requires user to manually put `ULWGL-launcher` as `$XDG_CONFIG_HOME/heroic/tools/runtimes/ulwgl`.
This may as well be a symlink

e.g
```
git clone https://github.com/open-wine-components/ULWGL-launcher ~/.config/heroic/tools/runtimes/ulwgl
```

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by imLinguin** [comment]
Heroic now requires only `ulwgl-run` file to be present in the `tools/runtimes/ulwgl` directory. The script will download the whole runtime as needed

**Comment by shelterx** [comment]
I tried this with a currently installed Epic Games Store game and got could not load ntdll.so (proton-ge-custom). It works fine without the ulwgl patches tho'. So it's something with the ulwgl launch causing this.

**Comment by Lx32** [comment]
> Heroic now requires only `ulwgl-run` file to be present in the `tools/runtimes/ulwgl` directory. The script will download the whole runtime as needed

How do I check if I'm using ULWGL? I put the script in the right folder and tried to launch the game with Proton GE 9.1 and I got no error. But from the log I cannot get any info on using the tool or not.

**Comment by shelterx** [comment]
> > Heroic now requires only `ulwgl-run` file to be present in the `tools/runtimes/ulwgl` directory. The script will download the whole runtime as needed
> 
> How do I check if I'm using ULWGL? I put the script in the right folder and tried to launch the game with Proton GE 9.1 and I got no error. But from the log I cannot get any info on using the tool or not.

You see it if you start heroic from the shell, when you start a game it should say something about ULWGL in the shell output.

**Comment by Lx32** [comment]
> > > Heroic now requires only `ulwgl-run` file to be present in the `tools/runtimes/ulwgl` directory. The script will download the whole runtime as needed
> > 
> > 
> > How do I check if I'm using ULWGL? I put the script in the right folder and tried to launch the game with Proton GE 9.1 and I got no error. But from the log I cannot get any info on using the tool or not.
> 
> You see it if you start heroic from the shell, when you start a game it should say something about ULWGL in the shell output.

I've checked but I got no information. It should work in mainline or I need some branch version of heroic?

**Comment by shelterx** [comment]
You have to build this PR yourself, right now it got conflicts with master so best is that you wait until it's merged.

**Comment by arielj** [comment]
Closing this one since https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3724 is a continuation of this

**Pull request closed without merging**
