### PR TITLE
1.9.4

### PR DESCRIPTION
**Pull request by flavioislima**
Just a few fixes while we work on 2.0.

-------------------------------------------------------------
Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by flavioislima** [comment]
@syto203 Hi!
Can you compile the latest legendary release for MacOS? and send me a link to download?
I want to include it in this new release.

Thanks!

**Review by Nocccer — DISMISSED** [review]
LGTM so far. Don't have the knowledge in web based languages like you, but maybe you like if someones looks over your code and check it :)

**Comment by flavioislima** [comment]
Closing this one since 1.9.4 makes no sense and I'll push 1.10 instead because of the amount of changes.

**Comment by syto203** [comment]
> @syto203 Hi! Can you compile the latest legendary release for MacOS? and send me a link to download? I want to include it in this new release.
> 
> Thanks!

srry couldnt get to it sooner.
here it is and i'll try to keep it updated
syto203@96632fafeb2ea3f6e442b82dec2308a0526c9b49

**Pull request closed without merging**
