### PR TITLE
Fix update dialog

### PR DESCRIPTION
**Pull request by Mariaboni**
Hello!! I updated the update dialog according to what we discussed on this issue last week: #3534 
image

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by flavioislima** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/doc/cla.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by Mariaboni** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by flavioislima — APPROVED** [review]
Looks good. Thanks for this contribution! :)

**Comment by arielj** [comment]
One thing that could improve the UX is to re-open the same dialog if the user clicked the `Changelog` button.

Because I imagine this scenario:
- you see the dialog
- click Changelog
- dialog closes and Changelog is displayed
- you have no way to trigger the update cause the dialog is gone

if we extract the whole function we can do something like:

```ts
autoUpdater.on('update-available', showAutoupdateDialog())
```

and then that function can call itself when the dialog is closed with the Changelog button

```ts
  if (response === 2) {
    shell.openExternal(
      'https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases'
    )
    showAutoupdateDialog()
  }
```

the dialog will be closed but will open again automatically I'm guessing

**Comment by flavioislima** [comment]
Closing this one in favor of #3598 that includes your comments @arielj

**Pull request closed without merging**
