### PR TITLE
macOS Dock Menu support

### LINKED ISSUE #4156: Dock Menu on macOS
### Problem description

The top bar icon of Heroric has two problems:

1. clicking it brings the app in focus (at least with Stage Manager on), and in combination with bartender it sometimes glitches out even more. (This is prolly a bug)
2. The top bar, especially on small Macbooks with a notch is already really full already, meaning it sometimes isn’t accessible.

### Feature description

Introducing [Dock Menus](https://developer.apple.com/design/human-interface-guidelines/dock-menus/), where you can basically have the same thing, but down below in the dock.

### Alternatives

Maybe fixing the auto in focus bug in the top bar.

### Additional information

If I have time I can try to write it myself? I probably won’t any time soon though.

### PR DESCRIPTION
**Pull request by LenaWil**
Implements support for macOS Dock Menus.

Original text:
A terrible two liner that I didn’t put through the linter to show that support for Dock Menu’s would be easy to implement.

I should probably improve it, but I first wanted to know if the devs are open to this at all before I actually spend time on this.

Closes #4156.

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [X] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by flavioislima** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/doc/cla.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by LenaWil** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by LenaWil** [comment]
The linting is failing because of http errors, not actual errors. Can someone rerun it when the servers are up again?

**Comment by LenaWil** [comment]
Repeating something I said on Discord:
Also I could make a separate menu for the Dock with the stop/quit option hidden, that would mean generating the menu twice though.

**Comment by CommandMC** [comment]
Adding this image posted on Discord to make it easier to picture how this looks for people on non-macOS:
image

**Review by CommandMC — APPROVED** [review]
Can't test this, but looks and sounds fine to me

**Pull request merged**
