### PR TITLE
[Fix] Epic games fails to install

### LINKED ISSUE #1789: Can't Install games from EPIC
### Describe the bug

After the login on my Epic Games account, trying to download Cyberpunk 2077, the error in the attachment appear twice, one alert over the other, preventing the installation

image

### Add logs

(18:08:39) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(18:08:39) INFO:    [Legendary]:       Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(18:08:39) INFO:    [Gog]:             GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(18:08:39) INFO:    [Backend]:         

Heroic Version: 2.4.2 Chopper
Legendary Version:  0.20.28 Dark Energy (hotfix #2)
OS: Zorin KERNEL: 5.15.0-46-generic ARCH: x64
CPU: AMD Ryzen 7 3700X 8-Core Processor @3.6 GOVERNOR: ondemand
RAM: Total: 31.27 GiB Available: 26.2 GiB
GRAPHICS: GPU0: NVIDIA GeForce RTX 3070 VRAM: 8192MB DRIVER: 510.85.02 
PROTOCOL: x11

(18:08:39) WARNING: [Backend]:         Protocol already registered.
(18:08:40) INFO:    [Backend]:         Checking for new Heroic Updates
(18:08:40) INFO:    [Frontend]:        Refreshing Library
(18:08:40) INFO:    [Legendary]:       Refreshing library...
(18:08:40) INFO:    [Legendary]:       Refreshing Epic Games...
(18:08:40) INFO:    [Backend]:         AreWeAntiCheatYet data downloaded
(18:08:41) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(18:08:43) INFO:    [Backend]:         Downloaded Winetricks
(18:08:43) INFO:    [Legendary]:       Updating game list
(18:08:43) INFO:    [Legendary]:       Game List Updated
(18:08:45) INFO:    [Legendary]:       Checking for game updates.
(18:08:45) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(18:08:46) INFO:    [Legendary]:       Found 0 game(s) to update
(18:08:46) INFO:    [Gog]:             Found 0 game(s) to update
(18:10:27) INFO:    [Legendary]:       Getting more details with 'legendary info'
(18:10:27) INFO:    [Legendary]:       Getting more details with 'legendary info'
(18:10:27) DEBUG:   [Backend]:         {"free":1606570401792,"diskSize":1967317549056,"message":"1.46 TiB / 1.79 TiB","validPath":true}
(18:10:27) DEBUG:   [Backend]:         {"free":1606569910272,"diskSize":1967317549056,"message":"1.46 TiB / 1.79 TiB","validPath":true}
(18:10:28) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --pretty-json info Ginger --platform Windows --json
(18:10:28) INFO:    [Legendary]:       Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --pretty-json info Ginger --platform Windows --json
(18:10:33) ERROR:   [Backend]:         SyntaxError: Unexpected end of JSON input
(18:10:36) ERROR:   [Backend]:         SyntaxError: Unexpected end of JSON input

### Steps to reproduce

1. Go to 'Library section'
2. Click on 'Download icon from the library menu'

### Expected behavior

The installation should start and complete

### Screenshots

image

### System Information

- OS Zorin OS 16.1
- Heroic Version 2.4.2

### Additional information

_No response_

### LINKED ISSUE #1790: Since the epic games hotfix installation of new games broken
### Describe the bug

Installation of new epic games broken.  Empty popup appears. the main window shows error message "cannot get game info"
Gog installation works flawless.

### Add logs

 
(21:30:35) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(21:30:36) INFO:    [Legendary]:       Legendary location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(21:30:36) INFO:    [Gog]:             GOGDL location: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(21:30:36) INFO:    [Backend]:

Heroic Version: 2.4.2 Chopper
Legendary Version:  0.20.28 Dark Energy (hotfix #2)
OS: Freedesktop.org KERNEL: 5.13.0-valve21.1-1-neptune-02211-gc54cda5a36f3 ARCH: x64
CPU: AMD Custom APU 0405 @1.82 GOVERNOR: schedutil
RAM: Total: 14.49 GiB Available: 11.83 GiB
GRAPHICS: GPU0: Device 163f VRAM: 512MB DRIVER:
PROTOCOL: x11

(21:30:36) INFO:    [Gog]:             Getting data about the user
(21:30:36) WARNING: [Backend]:         Failed to register protocol with OS.
(21:30:37) INFO:    [Backend]:         AreWeAntiCheatYet data downloaded
(21:30:37) INFO:    [Gog]:             Saved user data to config
(21:30:37) INFO:    [Frontend]:        Refreshing Library
(21:30:37) INFO:    [Legendary]:       Refreshing library...
(21:30:37) INFO:    [Legendary]:       Refreshing Epic Games...
(21:30:37) INFO:    [Gog]:             Getting GOG library
(21:30:38) INFO:    [Gog]:             Number of library pages: 1
(21:30:38) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(21:30:38) INFO:    [Gog]:             Saved games data
(21:30:39) INFO:    [Backend]:         Downloaded Winetricks
(21:30:40) INFO:    [Legendary]:       Updating game list
(21:30:40) INFO:    [Legendary]:       Game List Updated
(21:30:40) INFO:    [Legendary]:       Checking for game updates.
(21:30:40) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(21:30:41) INFO:    [Legendary]:       Found 0 game(s) to update
(21:30:41) INFO:    [Gog]:             Found 0 game(s) to update
(21:37:04) INFO:    [Legendary]:       Getting Info from Epic API
(21:37:04) INFO:    [Legendary]:       Getting Info from Epic API
(21:37:04) INFO:    [Legendary]:       Getting more details with 'legendary info'
(21:37:05) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --pretty-json info Quail --platform Windows --json
(21:37:06) INFO:    [Legendary]:       Getting more details with 'legendary info'
(21:37:06) INFO:    [Legendary]:       Getting more details with 'legendary info'
(21:37:06) DEBUG:   [Backend]:         {"free":264693055488,"diskSize":492501127168,"message":"246.51 GiB / 458.68 GiB","validPath":true}
(21:37:06) DEBUG:   [Backend]:         {"free":264693055488,"diskSize":492501127168,"message":"246.51 GiB / 458.68 GiB","validPath":true}
(21:37:06) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --pretty-json info Quail --platform Windows --json
(21:37:06) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --pretty-json info Quail --platform Windows --json
(21:37:08) ERROR:   [Backend]:         SyntaxError: Unexpected end of JSON input
(21:37:08) ERROR:   [Frontend]:        Cannot get game info
(21:37:09) ERROR:   [Backend]:         SyntaxError: Unexpected end of JSON input
(21:37:09) ERROR:   [Backend]:         SyntaxError: Unexpected end of JSON input
(21:40:03) INFO:    [Legendary]:       Getting more details with 'legendary info'
(21:40:04) INFO:    [Legendary]:       Running command: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary --pretty-json info Quail --platform Windows --json

### Steps to reproduce

1. Select game you want to install
2. Click on 'install
3. Empty popup appears 2 times
4. The main windows shows the error message

### Expected behavior

Game should be installed

### Screenshots

_No response_

### System Information

- steam OS 
- Heroic Version 2.4.2:

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by CommandMC**
Now using latest version from this PR:
https://github.com/derrod/legendary/pull/477

Closes #1789, closes #1790 

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by flavioislima** [comment]
Did you chmod +x both Linux and mac binaries?

**Comment by jacobrakestraw** [comment]
You are a good man commandmc

**Comment by CommandMC** [comment]
> Did you chmod +x both Linux and mac binaries?

Yup

**Review by Nocccer — APPROVED** [review]
Good catch!

**Review by flavioislima — APPROVED** [review]

**Pull request merged**
