### PR TITLE
[FIX] Remove isMac check for 32 bit dxvk

### PR DESCRIPTION
**Pull request by Etaash-mathamsetty**
32 bit dlls can run on mac os thanks to the wow64 implemented in crossover (and upstream wine). 

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [x] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by arielj** [comment]
I don't understand the reason of this change (I'm not versed in how all this dxvk stuff works and even less with mac)

I see some comments about this in discord but I don't know about this, how can I test this on my mac? what should I look for?

**Comment by Etaash-mathamsetty** [comment]
> I don't understand the reason of this change (I'm not versed in how all this dxvk stuff works and even less with mac so I don't understand the topic)
> 
> I see some comments about this in discord but I don't know about this, how can I test this on my mac? what should I look for?

run a 32 bit game that uses d3d, then check if it uses dxvk

**Comment by arielj** [comment]
i just tried with Flatout and the game works in the main branch but fails to launch with this branch

I'm attaching both logs: `...-errors.log` is the run with this branch, `...-lastPlay.log` is the one using main

for both cases I'm using wine-crossover 23 and in both cases it's creating a new prefix

maybe this change is fine for crossover but not for wine-crossover?

[1207658693-errors.log](https://github.com/user-attachments/files/16202510/1207658693-errors.log)
[1207658693-lastPlay.log](https://github.com/user-attachments/files/16202511/1207658693-lastPlay.log)

**Comment by Etaash-mathamsetty** [comment]
> i just tried with Flatout and the game works in the main branch but fails to launch with this branch
> 
> I'm attaching both logs: `...-errors.log` is the run with this branch, `...-lastPlay.log` is the one using main
> 
> for both cases I'm using wine-crossover 23 and in both cases it's creating a new prefix
> 
> maybe this change is fine for crossover but not for wine-crossover? I don't have the paid crossover to test it though
> 
> [1207658693-errors.log](https://github.com/user-attachments/files/16202510/1207658693-errors.log)
> [1207658693-lastPlay.log](https://github.com/user-attachments/files/16202511/1207658693-lastPlay.log)
> 
> EDIT: I tried with the latest wine-staging 9.11 that can be installed with heroic and I have the same error when launching the game with this branch and works fine in main

Seems like moltenvk doesn't support enough features to run dxvk?

**Comment by arielj** [comment]
Tested flatout again with this PR and reinstalling the game, new prefix, new everything, and it's now working.

**Review by flavioislima — APPROVED** [review]
LGTM

**Pull request merged**
