### PR TITLE
Add catalan (third attempt)

### PR DESCRIPTION
**Pull request by dragonDScript**
Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [x] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by flavioislima** [comment]
Have you finished the translations in weblate? last time I checked it was on around 50%

**Comment by dragonDScript** [comment]
Around 9X% or 100%

**Comment by flavioislima** [comment]
> Around 9X% or 100%

72% :P
image


Are you committing when you finish translating? maybe you're missing some keys after adding them.

**Comment by dragonDScript** [comment]
> > Around 9X% or 100%
> 
> 72% :P
> image
> 
> Are you committing when you finish translating? maybe you're missing some keys after adding them.

Oof. It may be that.

**Comment by dragonDScript** [comment]
99% now

**Comment by flavioislima** [comment]
Nice, you still need to add the language in three other places:
README (In the list of supported languages)
i18next-parser.config.js (on the array of locales)
main.js (on the list of supported languages)

**Comment by flavioislima** [comment]
> 99% now

Yes, saw that two strings are missing, the `Click To Update` and the not supported info. Those are important, don't forget :)

**Comment by dragonDScript** [comment]
> > 99% now
> 
> Yes, saw that two strings are missing, the `Click To Update` and the not supported info. Those are important, don't forget :)

ok, done

**Comment by dragonDScript** [comment]
Now I'm checking whetever if it works in a clean appimage

**Comment by flavioislima** [comment]
> Nice, you still need to add the language in three other places:
> README (In the list of supported languages)
> i18next-parser.config.js (on the array of locales)
> main.js (on the list of supported languages)

@dragonDScript I think you're just missing adding it to this list above and we are good to go

**Comment by dragonDScript** [comment]
Good to go

**Review by flavioislima — APPROVED** [review]

**Pull request merged**
