### PR TITLE
[Feature] Changelog Modal

### PR DESCRIPTION
**Pull request by GessioMori**
Based on this issue https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2049, this PR implements a modal to show changelog after installing or updating Heroic. It makes Heroic version number (on sidebar) clickable to show the same modal. Furthermore, it adds a  checkbox to general settings which the user can use to disable this feature.

How it works: Heroic version component checks if the changelog for the current version was already shown. If it wasn't, it fetches Github API to get the release information. It uses react-markdown to render the body of the release.

Noticed problems: currently, it is fetching twice after startup, but I think that is caused by unnecessary renders  caused by context changes.

P.S. This is the first time ever I'm contributing to a project, so if I made something wrong in the PR process, please message me and I will fix that.

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [x] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by Etaash-mathamsetty** [comment]
not sure if this is possible, but could you make the links clickable, so if you click on the link it redirects you to the PR, since right now, you have to manually copy and paste the link

**Comment by flavioislima** [comment]
@GessioMori thanks for that.
I will review and test it during the weekend. 😁
Can you also add some screenshots of the feature?

**Comment by flavioislima** [comment]
Tested here and looks good, thanks for that!

image

**Review by flavioislima — APPROVED** [review]
Good stuff! 
Valeu! ⚔️

**Pull request merged**
