### PR TITLE
[Fix] Add winetricks dependencies for Flatpak

### PR DESCRIPTION
**Pull request by Nocccer**
Adding dependencies winetrick needs.
Copied over from: https://github.com/flathub/com.valvesoftware.Steam.Utility.protontricks/blob/master/com.valvesoftware.Steam.Utility.protontricks.yml

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Review by imLinguin — APPROVED** [review]
Looks good to me. Keep in mind we also need to update manifest on Flathub.

Just little note to not forget :)

**Comment by flavioislima** [comment]
Actually you are not doing anything here. It will work locally but to fix on flatpak you need to open a PR here:
https://github.com/flathub/com.heroicgameslauncher.hgl

**Comment by Nocccer** [comment]
> Actually you are not doing anything here. It will work locally but to fix on flatpak you need to open a PR here: https://github.com/flathub/com.heroicgameslauncher.hgl

https://github.com/flathub/com.heroicgameslauncher.hgl/pull/21

**Comment by flavioislima** [comment]
Will merge this one to update our local flatpak build file as well 👍🏽

**Pull request merged**
