### PR TITLE
Refactor instantiation of electron stores

### PR DESCRIPTION
**Pull request by arielj**
This PR is just a refactor on how we use the electron stores in both the backend and the frontend.

We had a lot of repetition creating new Stores in every file that uses one. In this PR I moved them to only create the stores once in the backend and once in the frontend and share it between components and modules by imports.

For the backend, I split them in 3 groups: gog-specific stores, epic-specific stores, heroic-specific stores. GOG's and Epic's are in `gog/electron_stores.ts` and `legendary/electron_stores.ts`, heroic ones are defined in the constants.ts file.

For the frontend, I moved the instantiation of all stores to the `helper/electron_stores.ts` file.

I updated all files that were importing stuff and creating new stores to use the ones already created.

I tested many things:
- installing and uninstalling games for both gog and epic
- adding more wine versions
- time played
- changing settings

I would appreciate more tests of course!

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Review by flavioislima — DISMISSED** [review]
Looks pretty good! 💯 
Before merging though would be good to test on a clean install to see if nothing broke. 👍🏽

**Comment by flavioislima** [comment]
There is a conflict now after merging the previous one. After that we can merge 👍🏽

**Comment by arielj** [comment]
@flavioislima I fixed the conflicts, I still haven't have time to do a clean install (I don't know how to do a clean install without messing up my current configuration and games)

I can try later on a VM

**Comment by flavioislima** [comment]
You can just rename those folders:
`$HOME/.config/legendary` and `$HOME/.config/heroic` 
this is how I do it. :D

**Comment by arielj** [comment]
> You can just rename those folders: `$HOME/.config/legendary` and `$HOME/.config/heroic` this is how I do it. :D

thanks, I tested with that and everything seems to be working as expected, things I tried:
- log in
- hiding games
- installing wine versions
- installing/uninstalling a game
- changed settings
- closing/opening heroic to verify things are persisted

**Comment by flavioislima** [comment]
Great, so just fix the conflict and we can merge it :D

**Comment by arielj** [comment]
@flavioislima github won't let me merge this until it's approved

**Review by flavioislima — APPROVED** [review]

**Pull request merged**
