### PR TITLE
Correct various translations for installing DXVK-NVAPI

### PR DESCRIPTION
**Pull request by termdisc**
The Russian translation for installing DXVK-NVAPI incorrectly labeled it as just DXVK.

It currently says `Автоматически устанавливать/обновлять DXVK в префиксе` for both DXVK and DXVK-NVAPI.

### CODE REVIEW

**Comment by flavioislima** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/doc/cla.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by termdisc** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by arielj** [comment]
Translations must be fixed in Weblate https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Translations#how-to-translate-heroic

Then it will create a PR with updated translations for all languages.

We can merge a PR with string changes or they will be overrode by weblate in the future.

**Comment by termdisc** [comment]
Got it. I’ll do the edits over there

**Comment by termdisc** [comment]
I have made the relevant edits over on Weblate, but I cannot find where I can initiate a PR based on those changes. Can you direct me to where I need to go for that?

**Comment by termdisc** [comment]
Sounds good, thanks!

**Pull request closed without merging**
