### PR TITLE
[Fix] Steam Shortcuts / Make checkIfAlreadyAdded case-insensitive

### LINKED ISSUE #3124: Heroic may fail to detect entries it added to Steam
### Describe the bug

An entry added to Steam by Heroic can fail to be detected by Heroic if a user adds it to a collection or any other minor edit that rewrites its shortcuts.vdf entry.

### Add logs

```text
< no relevant logs available >
```

### Steps to reproduce

1. Open Heroic
2. Select game
3. Add to Steam
4. Restart Steam
5. Add game to collection
6. Heroic (possibly) no longer registers the game as added to Steam

### Expected behavior

Games that have had minor edits such as adding it to a collection should still be detected as added by Heroic

### Screenshots

_No response_

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: Windows

### Additional information

This seems like it is somewhat related to #2357 

Since Steam is apparently inconsistent in the usage of "appname", "appName", "AppName", etc. when Heroic adds an entry to Steam it will use one form but Steam may use another. Steam appears to be entirely case-insensitive in this regard so it doesn't affect it, but when it updates an entry to add it to a collection it will rewrite it to whatever form it uses and Heroic will no longer detect it.
I checked this by changing the form back and Heroic detects the entry again.

A possible fix would be to make Heroic case-insensitive as well.

One minor complication I could see with that fix is since it appears Heroic detects based entirely on game title, if a user happened to have another instance of an entry with that title (possibly a different version), then Heroic will incorrectly detect it as its own entry and could possibly delete it.

### PR DESCRIPTION
**Pull request by HazardousBackup**
This change should make checkIfAlreadyAdded insensitive to the case of 'AppName' so if it changes it'll still be recognized and able to be removed and not double added.

Fixes #3124 

Change is based on [this StackOverflow post](https://stackoverflow.com/a/47538066)

Tested but not on a completely clean install

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by flavioislima** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/doc/cla.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by HazardousBackup** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by arielj** [comment]
I'm curious, is heroic adding the information with the wrong case for the key? or is steam transforming them in some way?

because maybe we should make heroic use whatever case steam expects instead? do you have an example of this data with keys that are not `AppName`? maybe we should add the games to steam with `appname` as the key if that makes them all consistent for example

**Comment by HazardousBackup** [comment]
> I'm curious, is heroic adding the information with the wrong case for the key? or is steam transforming them in some way?
> 
> because maybe we should make heroic use whatever case steam expects instead? do you have an example of this data with keys that are not `AppName`? maybe we should add the games to steam with `appname` as the key if that makes them all consistent for example

It's a bit more than that based on #2030

Apparently Steam isn't 100% consistent on the use of case and can vary over time or OSes, but that doesn't matter to Steam because it doesn't appear to care about the case at all (you can use randomized case with no issues). However, Steam does like to convert entrees to whatever case is standard for it at the moment.

So Heroic can't really rely on just changing `AppName` to `appname` because it seems like it could change to `appName` or something else without warning later on.

**Comment by HazardousBackup** [comment]
I just realized that a change needs to be made to `removeNonSteamGame` as well. It uses the AppName value of the shortcut, which since it might be a different case could end up being undefined and so the AppID used for removing the artwork won't be correct.

**Comment by HazardousBackup** [comment]
I've committed the change to removeNonSteamGame and tested it on my install.
Before:
Add to Steam -> images added
Change Collection
Remove from Steam -> images stay

After:
Add to Steam -> images added
Change Collection
Remove from Steam -> images removed (as expected)

It's basically the same as the first change and I don't see any other points where the shortcuts file is being accessed that way, so it should be complete.

**Review by arielj — COMMENTED** [review]
maybe this is a bit nitpicky, but since we already have something similar in this function

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/src/backend/shortcuts/nonesteamgame/nonesteamgame.ts#L143

maybe we move getting the value to a function too for consistency:

```
function getAppName(object) {
  const foundKey = Object.keys(object).find((key) => key.toLowerCase() === 'appname') ?? 'AppName'
  return object[foundKey]
}
```

then you can do `return getAppName(shortcuts)` and `const appName = getAppName(surtcubOjb)`

**Comment by HazardousBackup** [comment]
@arielj Nitpicky or not, it's not a big deal and it helps with consistency. Had I noticed that other function then I likely would've implemented it the same way.

Bonus is that it helps keep the other functions cleaner.

**Review by arielj — APPROVED** [review]
Looks good to me :+1:

**Pull request merged**
