### PR TITLE
[General] Improvements in language selector when installing game

### PR DESCRIPTION
**Pull request by dawidgarus**
On game installation dialog
- Available languages are now displayed as human readable names instead of codes
- Attempt to select by default language that matches the language of the application interface

Preview:
Screenshot from 2022-03-17 01-18-39

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Review by flavioislima — APPROVED** [review]
Looks good. Will test later! 
@imLinguin take a look as well if you have time 👍🏽

**Comment by imLinguin** [comment]
Have you tested how it behaves for older games that use old depot system (V1)?

**Comment by dawidgarus** [comment]
> Have you tested how it behaves for older games that use old depot system (V1)? Those are mostly human readable by default.

I didn't test it with anything other than GOG games, because I don't own any Epic game that prompts for selecting language.
But I wrote the code to fail gracefully. If translation can't be find by `Intl` for any reason, it will fallback to original value.
As for default selected value, it will also fallback to selecting first on list, with one caveat - it may in some edge cases default "random" language.

**Comment by imLinguin** [comment]
Then it's going to work for V1 games too.

Good job ⚔️

**Pull request merged**
