### PR TITLE
[Tech] Updated GOGDL to fix DOSBOX Games

### PR DESCRIPTION
**Pull request by flavioislima**
Need to test this build on all 3 platforms before merging.

Games tested with WINE-GE:
- Tyrian 2000
- Ultima IV
- Ultima II
- BioMenace
- Elders Scrolls Arena
- Elders Scrolls Daggerfall

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Review by imLinguin — APPROVED** [review]

**Comment by flavioislima** [comment]
@imLinguin  it seems the setup it's not working with Proton, I believe this started with the latest refactors. 
It shows:
`/bin/sh: line 1: /home/flavio/.local/share/Steam/steamapps/common/Proton: No such file or directory`

If the setup is made using wine and then changing to proton makes it works.

**Comment by flavioislima** [comment]
Not related but ScummVM for windows games are not working as well, could be a similar issue?

**Comment by flavioislima** [comment]
Tested with Beneath a Steel Sky. The ScummVM starts but then closes without starting the game. Similar to what was happening with the dosbox games.

this is the Log:

```
Error Log:

wineserver: using server-side synchronization.

wine: Using setpriority to control niceness in the [-11,11] range

002c:fixme:winediag:LdrInitializeThunk wine-staging 7.0 is a testing version containing experimental patches.

002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.

007c:fixme:imm:ImeSetActiveContext (0x4803d0, 0): stub

007c:fixme:imm:ImmReleaseContext (0000000000010020, 00000000004803D0): stub

010c:fixme:imm:ImeSetActiveContext (0x4403d0, 1): stub

010c:fixme:imm:ImmReleaseContext (0000000000020068, 00000000004403D0): stub

0024:fixme:thread:GetThreadUILanguage : stub, returning default language.

0024:fixme:pulse:pulse_channel_map_to_channel_mask Unhandled channel aux0

0024:fixme:pulse:pulse_channel_map_to_channel_mask Unhandled channel aux1

0024:fixme:imm:ImmReleaseContext (00010084, 02C60030): stub

0024:fixme:msctf:ThreadMgr_ActivateEx Unimplemented flags 0x4

0024:fixme:imm:ImeSetCompositionString PROBLEM: This only sets the wine level string

0024:fixme:imm:ImeSetCompositionString Reading string unimplemented

0024:fixme:imm:NotifyIME NI_CLOSECANDIDATE

0024:fixme:imm:ImeSetActiveContext (0x2c60030, 1): stub

0024:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION

0128:fixme:d3d:state_linepattern_w Setting line patterns is not supported in OpenGL core contexts.

wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.

0024:fixme:shell:propertystore_SetValue (02B22D90)->(01944AE8 028FA738): stub

0024:fixme:shell:propertystore_Commit (02B22D90): stub

0024:fixme:shell:SHAddToRecentDocs Unsupported flags: 6

012c:fixme:d3d:state_linepattern_w Setting line patterns is not supported in OpenGL core contexts.

0024:fixme:explorerframe:taskbar_list_SetProgressState iface 029DD1B0, hwnd 00010084, flags 4 stub!

0024:fixme:explorerframe:taskbar_list_SetProgressValue iface 029DD1B0, hwnd 00010084, ullCompleted 1, ullTotal 1 stub!

0024:fixme:imm:ImeSetCompositionString PROBLEM: This only sets the wine level string

0024:fixme:imm:ImeSetCompositionString Reading string unimplemented

0024:fixme:imm:NotifyIME NI_CLOSECANDIDATE

Game Log:

Using configuration file: ..\beneath.ini

Launch command: ['/home/flavio/.config/heroic/tools/wine/Wine-GE-Proton7-15/bin/wine', '/mnt/hdd/Games/Heroic/Beneath a Steel Sky/scummvm/scummvm.exe', '-c', '..\\beneath.ini', 'beneath']


```

**Comment by imLinguin** [comment]
I remember now, there is a setup instruction to write that .ini file. I think it's not working properly in Heroic.

**Comment by flavioislima** [comment]
Well, the .ini file is there.

**Comment by imLinguin** [comment]
What about the contents? Is it containing the data provided in script instruction?

**Comment by imLinguin** [comment]
The instructions are in .script file. I'll be able to test the game myself tomorrow.

**Pull request merged**
