### PR TITLE
Change submenu to be always visible on game page

### PR DESCRIPTION
**Pull request by flavioislima**
I got some user feedback about how difficult its sometimes to realise that we have a submenu under the game page. Some people think that that settings button is to open the game settings. so I think its better to keep it always visible from now on.

image

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Created / Updated Tests
- [ ] Created / Updated documentation

Tested on a Clean Install with AppImage:
- [ ] Login
- [ ] Download a Game
- [ ] Import a Game
- [ ] Launch Default config
- [ ] Launch Personalized Config
- [ ] Launch wine
- [ ] Launch Proton
- [ ] Launch Custom Proton
- [ ] Launch Tools (Winetricks and Winecfg)
- [ ] Uninstall Game
- [ ] Move Game
- [ ] Languages (Test if no translation stopped working)

### CODE REVIEW

**Review by Nocccer — APPROVED** [review]
Looks good to me

**Review by adityaruplaha — APPROVED** [review]
Don't particularly like it, but it's better than what we have currently.

**Comment by dragonDScript** [comment]
We'd need to change the appearance of it.

**Review by dragonDScript — CHANGES_REQUESTED** [review]
Why this and not a sub menu?

**Comment by flavioislima** [comment]
> We'd need to change the appearance of it.

check new design

**Comment by flavioislima** [comment]
> Why this and not a sub menu?

Because some people were not finding this. So sometimes we need them to send us the latest log and they can't find it. Or even ask how they can open the game page from heroic, etc.

**Pull request merged**
