### PR TITLE
Update Electron to 20.0.1

### PR DESCRIPTION
**Pull request by Etaash-mathamsetty**
This update seems to make it much easier to run heroic games under wayland without xwayland, so I guess it's good to update before stable 2.4.0
edit: just tried it out under wayland, I didn't run a game or anything, but the ui works well

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [x] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by flavioislima** [comment]
Heroic is running in Wayland just fine for several releases already, it didn't start with Electron 19, probably around Electron 14, and 15.

**Comment by Etaash-mathamsetty** [comment]
> Heroic is running in Wayland just fine for several releases already, it didn't start with Electron 19, probably around Electron 14, and 15.

I just said that it's easier that's it lol

**Comment by Nocccer** [comment]
We can switch to new electron version after stable release of beta. So we can test this electron version before.

**Comment by flavioislima** [comment]
@Etaash-mathamsetty have you tested the most Heroic features after updating to Electron 20?
Most of the time is ok to upgrade but it is good to read the release notes and test to see if there are no breaking changes.

**Comment by Etaash-mathamsetty** [comment]
> @Etaash-mathamsetty have you tested the most Heroic features after updating to Electron 20? Most of the time is ok to upgrade but it is good to read the release notes and test to see if there are no breaking changes.

it seems to be working fine, would probably need additional testing from others to confirm

**Review by flavioislima — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
