### PR TITLE
[Feature] Add option to add/edit/delete categories from categories dropdown

### PR DESCRIPTION
**Pull request by arielj**
Fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3415
Fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3406

This PR adds a new dialog to add/edit/delete categories without having to right click a game card.

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/188464/93538965-5b6a-4f1f-9d4e-ed38e45a0c44

Some notes:
- I ordered the categories alphabetically for now, at some point we can let users reorder them but currently it the order changes when editing which is not good
- The video was recorded before the last changes so some issue that can be seen in the videos are fixed

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by flavioislima** [comment]
Codewise and feature-wise looks good.
But this design I think doesn't work:
image


I think both buttons should be at the same place: bottom.
try something like:
Select ALL
Manage Categories.

I think that would look better.

**Comment by arielj** [comment]
> Codewise and feature-wise looks good. But this design I think doesn't work: image
> 
> I think both buttons should be at the same place: bottom. try something like: Select ALL Manage Categories.
> 
> I think that would look better.

just pushed this change

**Comment by flavioislima** [comment]
Tested here and looks good, will merge to add to the next release.

One minor improvement for the future though: When clicking on Select All it also selects the 'Uncategorized' this has the same effect as selecting none.

**Review by flavioislima — APPROVED** [review]
LGTM

**Pull request merged**
