### PR TITLE
[FIX] Don't unset DOTNET_ROOT for wine

### PR DESCRIPTION
**Pull request by Etaash-mathamsetty**
Turns out these dotnet variables are not supposed to be set by the distro, it's a distro packaging bug. It has been fixed for arch linux, but not fixed for fedora yet. 

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [x] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by flavioislima** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/doc/cla.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by Etaash-mathamsetty** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by arielj** [comment]
@Etaash-mathamsetty , really, you have to make better PR descriptions

This change was merged without a clear reason back then https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3041

the description said it was urgent, not it's reverted and there's no clear explanation either (how can we test this?)


you have to be more clear cause it's impossible to know the things you don't explain

**Comment by Etaash-mathamsetty** [comment]
> @Etaash-mathamsetty , really, you have to make better PR descriptions
> 
> This change was merged without a clear reason back then #3041
> 
> the description said it was urgent, not it's reverted and there's no clear explanation either (how can we test this?)
> 
> you have to be more clear cause it's impossible to know the things you don't explain

there is a clear reason, if dotnet sdk is installed -> game breaks, how much clearer can it be? Now the workaround can be removed since the underlying issue is being fixed

**Comment by arielj** [comment]
> > @Etaash-mathamsetty , really, you have to make better PR descriptions
> > This change was merged without a clear reason back then #3041
> > the description said it was urgent, not it's reverted and there's no clear explanation either (how can we test this?)
> > you have to be more clear cause it's impossible to know the things you don't explain
> 
> there is a clear reason, if dotnet sdk is installed -> game breaks, how much clearer can it be? The PR then goes and adds a workaround to the problem. Now the workaround can be removed since the underlying issue is being fixed

what I mean is, in that other PR commandmc had to ask you for a game with the problem to understand it better and you said that you believed baldur's gate was one (giving the impression you were not sure either), but it happened in the comments, not in the PR description

now you are saying something was fixed in arch but not in fedora, does that mean changing this in heroic will be a problem for fedora users if fedora didn't fix this yet? since you mention arch and fedora, do you know if it's something to worry for other distros?

**Comment by Etaash-mathamsetty** [comment]
> > > @Etaash-mathamsetty , really, you have to make better PR descriptions
> > > This change was merged without a clear reason back then #3041
> > > the description said it was urgent, not it's reverted and there's no clear explanation either (how can we test this?)
> > > you have to be more clear cause it's impossible to know the things you don't explain
> > 
> > 
> > there is a clear reason, if dotnet sdk is installed -> game breaks, how much clearer can it be? The PR then goes and adds a workaround to the problem. Now the workaround can be removed since the underlying issue is being fixed
> 
> what I mean is, in that other PR commandmc had to ask you for a game with the problem to understand it better and you said that you believed baldur's gate was one (giving the impression you were not sure either), but it happened in the comments, not in the PR description
> 
> now you are saying something was fixed in arch but not in fedora, does that mean changing this in heroic will be a problem for fedora users if fedora didn't fix this yet? should we wait for confirmation this is fixed in fedore before merging? since you mention arch and fedora, do you know if it's something to worry for other distros?

as far as I know it's only fedora, ubuntu's package was fine the entire time, the arch one recently got fixed

**Pull request closed without merging**
