### PR TITLE
New Setting to Add Custom Wine/Proton binary

### PR DESCRIPTION
**Pull request by flavioislima**
This adds a new setting on the global configuration to select custom Proton/Wine binaries. If the binary is a proton one, it will be shown as `Proton Custom - .../path/proton`. If Wine, it will show `Wine Custom - ...`

PS.: Ignore the first 11 commits since I branched out of `some fixes` branche so those commits are on `main` already.

### CODE REVIEW

**Comment by flavioislima** [comment]
image

**Comment by flavioislima** [comment]
Hello! Need new translations again:
```
"addpath": "Add New Path",
"removepath": "Remove Path"
"customWineProton": "Custom Wine/Proton Paths",
"customWine": "Select the Wine or Proton Binary"
```

I'm thinking about moving to another platform to improve these translations requests so it will be easier in the future :)
@onadrog @iWeaker4you @D3SOX @skowr @ianwijma @lol28 @BiRo96 @entaromia

**Comment by D3SOX** [comment]
```json
"addpath": "Neuen Pfad hinzufügen",
"removepath": "Pfad entfernen"
"customWineProton": "Benutzerdefinierte Wine/Proton Pfade",
"customWine": "Wähle die Wine oder Proton Binärdatei"
```
I can recommend Weblate or Crowdin for translations. They're free for FOSS projects.

**Comment by flavioislima** [comment]
> I can recommend Weblate or Crowdin for translations. They're free for FOSS projects.

Nice! I'll take a look 👍🏽

**Comment by BiRo96** [comment]
​"addpath": "Új útvonal hozzáadása",
"removepath": "Útvonal eltávolítása"
"customWineProton": "Egyéni Wine/Proton útvonalak ",
"customWine": "Válaszd ki a Wine vagy Proton Binary-t"

**Comment by entaromia** [comment]
```
"addpath": "Yeni Yol Ekle",
"removepath": "Yolu Kaldır"
"customWineProton": "Özel Wine/Proton Yolları",
"customWine": "Wine ya da Proton Dosyasını Seçin"
```

**Comment by onadrog** [comment]
Fr:

"addpath": "Ajouter un nouveau chemin",
"removepath": "Supprimer le chemin"
"customWineProton": "Chemins pour les Wine/Proton  Custom",
"customWine": "Sélectionner le binaire Wine ou Proton"

**Comment by lol28** [comment]
"addpath": "Добавить новый путь",
"removepath": "Удалить путь"
"customWineProton": "Пользовательские пути Wine/Proton",
"customWine": "Выберите исполняемый файл Wine или Proton"

**Comment by skowr** [comment]
Polish translation:

"addpath": "Dodaj nową ścieżkę",
"removepath": "Usuń ścieżkę"
"customWineProton": "Niestandardowe ścieżki Wine/Proton",
"customWine": "Wybierz plik uruchomieniowy Wine albo Proton"

**Review by adityaruplaha — DISMISSED** [review]
Everything looks fine code wise. Ready for merge.

**Review by ianwijma — DISMISSED** [review]
Looks good :>

**Comment by vitor180396** [comment]
PT-BR:
"addpath": "Adicionar novo caminho",
"removepath": "Remover caminho"
"customWineProton": "Caminho personalizado do Wine/Proton",
"customWine": "Selecione o binário do Wine ou Proton"

**Review by onadrog — DISMISSED** [review]

**Pull request merged**
