### PR TITLE
[GOG] add support for V1 setup instructions

### PR DESCRIPTION
**Pull request by imLinguin**
This PR makes all games I tested and had issues with before, **working**. Additional testing of V1 games is welcome of course. 

Some code is duplicated here, but I nevertheless want to change handling of those instructions in the future  
And use cached manifests instead of getting them online

Also fixed issues with some V2 games like `The Witcher`, by looking for executable in support directory, when it doesn't exist in game dir

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by imLinguin** [comment]
Also added gogdl update, which only changes build ids for V1 games returned in `info` command

**Comment by arielj** [comment]
the localappdata change works fine here :+1:

I couldn't try a V1 game yet though

**Review by flavioislima — APPROVED** [review]
LGTM

**Comment by imLinguin** [comment]
I'll still need to add `{userdocs}` path support. Let's not merge untill it's done

**Comment by arielj** [comment]
do we want this change against stable? or is it better for main? not sure how stable this change is but maybe it's a good idea if it goes in the next stable release since I tested only a few GOG games and found 2 with these issues with the paths, maybe it's common

**Comment by arielj** [comment]
The only game I've found in my library that is a v1 is `The Elder Scrolls Adventures: Redguard` but it fails to fetch the install info with:

```
[DOWNLOAD_MANAGER] INFO: Checking compatibility of The Elder Scrolls Adventures: Redguard with windows
[DOWNLOAD_MANAGER] INFO: Game is compatible
[DOWNLOAD_MANAGER] INFO: Depot version: 1
[API] INFO: Getting Dependencies repository
[API] INFO: Getting repository manifest
Traceback (most recent call last):
  File "gogdl/cli.py", line 50, in <module>
  File "gogdl/cli.py", line 46, in main
  File "gogdl/dl/manager.py", line 40, in calculate_download_size
  File "gogdl/dl/manager.py", line 216, in collect_depots
KeyError: 'url'
[647302] Failed to execute script 'cli' due to unhandled exception!
```

I understand this PR is NOT intended to fix that error, right?

**Comment by imLinguin** [comment]
Build that should solve Redguard issues

https://github.com/Heroic-Games-Launcher/heroic-gogdl/actions/runs/3823538990

Let me know if that works, then I'll update gogdl binaries and we'll be ready to finally merge

**Comment by arielj** [comment]
I can confirm the `userdocs` path variable works works fine now :+1:

**Comment by arielj** [comment]
> Build that should solve Redguard issues
> 
> https://github.com/Heroic-Games-Launcher/heroic-gogdl/actions/runs/3823538990
> 
> Let me know if that works, then I'll update gogdl binaries and we'll be ready to finally merge

I can confirm that binary fixes the issue with `The Elder Scrolls  Adventures: Redguard` failing to fetch install info :+1:

**Comment by arielj** [comment]
I do have a problem trying to install the game, the % goes over 100% and never stops, I'm attaching a log (looks like some checksum is not matching and it keeps downloading the files again and again?)

Not sure if it's something specific about this game or what.

[gogdl-2023-01-03T03_04_53.170Z.log](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/10334171/gogdl-2023-01-03T03_04_53.170Z.log)

**Comment by imLinguin** [comment]
Apparently I broke things on the way,
this should solve it

**Comment by arielj** [comment]
> Apparently I broke things on the way, this should solve it https://github.com/Heroic-Games-Launcher/heroic-gogdl/actions/runs/3825415079

it is better now but still not working, now it gets to `100.27%` or progress and changes to `Processing files, please wait` in heroic's sidebar, but it never ends

and I see this error in the logs at some point:

```
Traceback (most recent call last):
  File "gogdl/cli.py", line 50, in <module>
  File "gogdl/cli.py", line 46, in main
  File "gogdl/dl/manager.py", line 27, in download
  File "gogdl/dl/manager.py", line 242, in perform_download
  File "gogdl/dl/manager.py", line 331, in perform_download_V1
KeyError: 'link'
[77319] Failed to execute script 'cli' due to unhandled exception!
```

**Comment by arielj** [comment]
I can confirm this fixes the issues for `Warhammer: Shadow of the Horned Rat` with the registry values with `""` as the name!

**Comment by arielj** [comment]
I can confirm this fixes all the issue with The Elder Scrolls Adventures: Redguard too!

**Comment by arielj** [comment]
should we merge this into stable instead of main? this fixes many things for gog games

**Review by arielj — APPROVED** [review]

**Pull request merged**
