### PR TITLE
README: Add Shields + minor fixes.

### PR DESCRIPTION
**Pull request by Flonky**
Replaced things with Shields & made minor fixes

### CODE REVIEW

**Comment by Flonky** [comment]
To do

- [ ]  Add Patreon Badge
- [ ] Add kofi badge

**Comment by Flonky** [comment]
Patreon Has a weird rendering bug, gotta fix that

**Comment by Flonky** [comment]
Seems to have been my browser, doesn't seem to occur anymore

**Review by adityaruplaha — APPROVED** [review]

**Review by flavioislima — APPROVED** [review]
looks really good! Can merge whenever you're ready :)

**Pull request merged**
