### PR TITLE
electron: Replace isOnline with navigator.onLine.

### PR DESCRIPTION
**Pull request by adityaruplaha**
This might break stuff. Also I'm currently incapable of regenerating the lockfile due to complications of going from yarn 2 to yarn 1 again (locally).

### CODE REVIEW

**Comment by flavioislima** [comment]
> This might break stuff. Also I'm currently incapable of regenerating the lockfile due to complications of going from yarn 2 to yarn 1 again (locally).

I think since this is another feature branch, would be ideal to start the branch from main to avoid conflicts with the lockfile. 👍🏽

**Comment by adityaruplaha** [comment]
> > This might break stuff. Also I'm currently incapable of regenerating the lockfile due to complications of going from yarn 2 to yarn 1 again (locally).
> 
> I think since this is another feature branch, would be ideal to start the branch from main to avoid conflicts with the lockfile. 👍🏽

Exactly what I did. But rebuiling packages takes very, very long.

**Comment by flavioislima** [comment]
> > > This might break stuff. Also I'm currently incapable of regenerating the lockfile due to complications of going from yarn 2 to yarn 1 again (locally).
> > 
> > 
> > I think since this is another feature branch, would be ideal to start the branch from main to avoid conflicts with the lockfile. 👍🏽
> 
> Exactly what I did. But rebuiling packages takes very, very long.

I think for you that don't have a good internet speed, PNPM should be the ideal since it wont be downloading new stuff all the time. I guess would be worth to try.

**Review by flavioislima — APPROVED** [review]
Looks good 👍🏽

**Pull request merged**
