### PR TITLE
[Bug]: Check shortcuts.vdf keys case insensitive to avoid false corruption detection.

### LINKED ISSUE #2030: Adding to Steam can fail due to error checking that isn't required
### Describe the bug

Trying to add games to steam throws this error in the log
`(12:20:30) ERROR:   [Shortcuts]:        Can't remove "Goat Simulator 3" from Steam user "<redacted>". "C:\Program Files (x86)\Steam\userdata\<redacted>\config\shortcuts.vdf" is corrupted!`

`One of the game entries is missing the AppName parameter!`

the thing is, my shortcuts.vdf isn't corrupt, it just contained an entry like this:
```
	{
		"appid" "-1493849556"
		"appName" "Dolphin Emulator"
		"exe" "\"E:\\NintendoEmulation\\SteamDolphin\\Dolphin.exe\""
		"StartDir" "E:\\NintendoEmulation\\SteamDolphin\\"
		"icon" "E:\\NintendoEmulation\\Tools\\Dolphin icon.png"
		"ShortcutPath" ""
		"LaunchOptions" ""
		"IsHidden" "0"
		"AllowDesktopConfig" "1"
		"AllowOverlay" "1"
		"OpenVR" "0"
		"Devkit" "0"
		"DevkitGameID" ""
		"DevkitOverrideAppID" "0"
		"LastPlayTime" "1666485127"
		"FlatpakAppID" ""
		"tags"
		{
			"0" "favorite"
			"1" "Emulators"
		}
	}
```
Notice how it has `appName`, but not `AppName` or `appname`, this is due to the error checking not properly checking case insensitivity.
This shortcut does work on steam, so the error checking is at fault here.

IMO, its not really on this program to check for valid VDF entries, it should just add the entry, and possibly warn the user that the shortcuts file is potentially corrupt, and so they might need to go delete the file.

### Add logs

(12:20:31) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:32) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:33) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:33) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:34) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:35) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:35) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:36) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:36) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:37) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:37) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:38) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:39) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:39) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:40) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:41) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:41) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:42) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:42) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:43) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:44) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:44) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:45) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:45) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:46) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:47) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:47) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:48) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:48) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:49) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:50) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:50) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:51) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:51) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:52) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:53) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:53) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:54) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:55) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:55) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:56) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:56) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:57) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:58) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:58) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:59) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:20:59) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:00) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:00) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:01) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:02) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:02) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:03) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:04) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:04) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:05) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:05) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:06) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:07) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:07) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:08) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:08) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:09) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:10) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:10) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:11) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:12) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:12) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:13) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:14) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:14) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:15) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:15) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:16) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:17) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:17) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:18) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:18) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:19) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:20) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:20) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:21) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:21) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:22) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:23) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:23) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:24) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:24) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:25) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:26) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:26) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:27) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:28) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:28) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:29) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:29) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:30) INFO:    [Shortcuts]:        Prepare Steam images for Goat Simulator 3
(12:21:31) WARNING: [Shortcuts]:        Goat Simulator 3 could not be added to all found Steam users.
(12:21:31) ERROR:   [Shortcuts]:        Can't add "Goat Simulator 3" to Steam user "<steamuserid>". "C:\Program Files (x86)\Steam\userdata\<steamuserid>\config\shortcuts.vdf" is corrupted!
One of the game entries is missing the AppName parameter!
One of the game entries is missing the AppName parameter!
One of the game entries is missing the AppName parameter!
One of the game entries is missing the AppName parameter!

### Steps to reproduce

Add to steam with a "corrupted" shortcuts.vdf

### Expected behavior

It should add to my shortcuts.vdf

### Screenshots

_No response_

### System Information

Windows 11

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Nocccer**
Should fix #2030 

@Zarklord @rodrigovda Please test the windows build of this PR, to confirm it fixes the issue.

- [x] Tested by @rodrigovda for windows

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by rodrigovda** [comment]
> Should fix #2030
> 
> @Zarklord @rodrigovda Please test the windows build of this PR, to confirm it fixes the issue.
> 

I am sorry but I'm not that knowledgeable in GitHub or such, How would I do this? Do I need to recompile everything myself? I'm not a programmer, I have some knowledge of how to code and compile, but I don't know so much as to knowing how to compile this, (I've always wanted to learn, but it's not that simple, as I'm sure you know hehe). If it's simple to do, would you kindly help me do it?

**Comment by Nocccer** [comment]
> > Should fix #2030
> > @Zarklord @rodrigovda Please test the windows build of this PR, to confirm it fixes the issue.
> 
> I am sorry but I'm not that knowledgeable in GitHub or such, How would I do this? Do I need to recompile everything myself? I'm not a programmer, I have some knowledge of how to code and compile, but I don't know so much as to knowing how to compile this, (I've always wanted to learn, but it's not that simple, as I'm sure you know hehe). If it's simple to do, would you kindly help me do it?

Sorry here is the link to the new win-portable version with the fix:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/suites/10421579940/artifacts/515131818

**Comment by rodrigovda** [comment]
I tested it and I can confirm it works correctly.

- [x]  Tested the feature and it's working on a current and clean install.
 
- [x]  Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)

Note: I found an issue when testing "Moving" games but that's an issue that exists in the main branch already and has nothing to do with this. I'll open a new Issue right away.

PS:
> Every pull-request build new binaries which can be downloaded to test fixes upfront.

Oh thank you, how could I find it myself for future reference?

**Comment by Nocccer** [comment]
> I tested it and I can confirm it works correctly.
> 
> - [x]  Tested the feature and it's working on a current and clean install.
>  
> - [x]  Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
> 
> Note: I found an issue when testing "Moving" games but that's an issue that exists in the main branch already and has nothing to do with this. I'll open a new Issue right away.
> 
> PS:
> > Every pull-request build new binaries which can be downloaded to test fixes upfront.
> 
> Oh thank you, how could I find it myself for future reference?

Under the check there are workflows. Find the workflow for the windows build and navigate to it. There should be a button summary. If you press summary you should see a link to the binaries somewhere at the bottom.

**Pull request merged**
