### PR TITLE
include vite in build instructions

### PR DESCRIPTION
**Pull request by lever1209**
fix for #2139

adds dependency vite to build instructions

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by CommandMC** [comment]
Uh, Vite should be auto-installed when running `yarn`/`npm install`, no?

**Comment by lever1209** [comment]
it may have at some point, but it hasnt during my testing

**Comment by lever1209** [comment]
interesting, i think vite should still be listed in some way

i wasnt aware running yarn by itself sorted out dependencies, but doesnt do so when building like how gradle does

**Comment by CommandMC** [comment]
> interesting, i think vite should still be listed in some way

Well, it's listed in the "Web Technologies" section of the README. Other than that, it's not really anything special. You'd get similar errors if you'd miss any other package in the dependencies

> i wasnt aware running yarn by itself sorted out dependencies, but doesnt do so when building like how gradle does

The lines right below the ones you edited mention this:

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/aa98cf2455cd2e29a9f7819b3d835f03c4abc5aa/README.md?plain=1#L216

**Comment by lever1209** [comment]
i was under the impression all it would do is the same as running `yarn dist:linux` where instead of building something, it would just verify deps and the project, not install deps as well

**Comment by lever1209** [comment]
for all i knew vite wasnt even needed because it wasnt listed, so if i manually installed all the deps listed, yknow, i wouldnt have to verify the deps are installed and it would work

anyway, ill just leave it up to the maintainers, maybe they can come up with a better solution

**Comment by CommandMC** [comment]
> for all i knew vite wasnt even needed because it wasnt listed

Every dependency (along with its compatible version) is listed in `package.json`. But you don't have to worry about this, since `yarn`/`npm install` will install everything for you

> so if i manually installed all the deps listed, yknow, i wouldnt have to verify the deps are installed and it would work

And if you instead just *ran the command that the README tells you to run*, you wouldn't have to worry about any of this. This is just simply how this system works, it isn't our fault if you don't follow the instructions, be it on purpose or because of a misunderstanding

**Pull request closed without merging**
