### PR TITLE
[Fix] Update dualsense controller mappings

### LINKED ISSUE #1584: incorrect/outdated button mappings for dualsense controller
### Describe the bug

I have a dualsense controller and the moment I press any trigger, heroic games launcher gets stuck scrolling up and there is no way to fix it other than restarting the app through the system tray

### Add logs
```
(17:05:20) INFO:    [Legendary]:       Running command: /tmp/.mount_Heroic15ClAN/resources/app.asar.unpacked/build/bin/linux/legendary --version
(17:05:20) INFO:    [Legendary]:       Legendary location: /tmp/.mount_Heroic15ClAN/resources/app.asar.unpacked/build/bin/linux/legendary
(17:05:20) INFO:    [Gog]:             GOGDL location: /tmp/.mount_Heroic15ClAN/resources/app.asar.unpacked/build/bin/linux/gogdl
(17:05:20) INFO:    [Backend]:         

Heroic Version: 2.4.0-beta.2 Caesar Clown
Legendary Version:  0.20.27 Dark Energy (hotfix)
OS: Arch KERNEL: 5.18.12-arch1-1 ARCH: x64
CPU: AMD Ryzen 7 4700U with Radeon Graphics @2 GOVERNOR: schedutil
RAM: Total: 15 GiB Available: 7.42 GiB
GRAPHICS: GPU0: gfx90c:xnack- VRAM: 512MB DRIVER:  
PROTOCOL: wayland

(17:05:20) INFO:    [Gog]:             Getting data about the user
(17:05:21) WARNING: [Backend]:         Protocol already registered.
(17:05:22) INFO:    [Backend]:         AreWeAntiCheatYet data downloaded
(17:05:22) INFO:    [Gog]:             Saved user data to config
(17:05:22) INFO:    [Frontend]:        Refreshing Library
(17:05:22) INFO:    [Legendary]:       Refreshing library...
(17:05:22) INFO:    [Legendary]:       Refreshing Epic Games...
(17:05:22) INFO:    [Gog]:             Getting GOG library
(17:05:22) INFO:    [Legendary]:       Running command: /tmp/.mount_Heroic15ClAN/resources/app.asar.unpacked/build/bin/linux/legendary list
(17:05:22) INFO:    [Gog]:             Number of library pages: 1
(17:05:23) INFO:    [Gog]:             Saved games data
(17:05:23) INFO:    [Legendary]:       Updating game list
(17:05:23) INFO:    [Legendary]:       Game List Updated
(17:05:24) INFO:    [Legendary]:       Checking for game updates.
(17:05:24) INFO:    [Legendary]:       Running command: /tmp/.mount_Heroic15ClAN/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(17:05:24) INFO:    [Backend]:         Downloaded Winetricks
(17:05:24) INFO:    [Legendary]:       Found 0 game(s) to update
(17:05:24) INFO:    [Gog]:             Found 0 game(s) to update
```

### Steps to reproduce

1. open heroic games launcher
2. press any trigger

### Expected behavior

right thumbstick should control scrolling not the triggers

### Screenshots

_No response_

### System Information

- OS arch linux
- Heroic Version latest on beta branch

### Additional information

I am pretty sure this is caused by outdated controller mappings or the usage of the wrong controller mapping

### PR DESCRIPTION
**Pull request by Etaash-mathamsetty**
fix the dualsense controller mappings
closes #1584
- [x] Tested the feature and it's working on a current and clean install.
- [x] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by Etaash-mathamsetty** [comment]
closes #1584

**Comment by Etaash-mathamsetty** [comment]
ignore the failed mac os build, github actions ran into some error for some reason

**Comment by imLinguin** [comment]
I didn't use the controller in heroic much. So here is what buttons do on game card since I am not sure if they are correct:

Triangle - open selected game page
Circle - Back
Square - context menu
X - pressing buttons

If those are expected actions, then it's working
Looks like Chromium finally has proper support for that controller - sticks are mapped correctly as axes

**Comment by flavioislima** [comment]
I just tested the PR and this is what I found:
- The issue with the L3/R3 is gone
- The Virtual Keyboard opens BUT the input doesn't work so its not possible to search for anything
- Other buttons are doing whats expected: Triangle open the game page and X executes the action on the selected button.

**Review by flavioislima — CHANGES_REQUESTED** [review]
I think the issue with the virtual keyboard should be fixed before merging it.

**Comment by arielj** [comment]
I'll check the virtual keyboard issue, shouldn't be related to this changes so this is good to merge

**Review by arielj — APPROVED** [review]

**Comment by arielj** [comment]
@flavioislima I wanted to merge this but it doesn't let me do it, it says we can't unless the requested changes are addressed (but I fixed the virtual keyboard issue in another PR), I think you have to either approve or merge this yourself

**Review by flavioislima — APPROVED** [review]

**Pull request merged**
