### PR TITLE
Make actions_font_family_no_default and content_font_family_no_default more translation-friendly

### PR DESCRIPTION
**Pull request by jjanuszkiewicz**
Replace string concatenation with i18n interpolation in `actions_font_family_no_default` and `content_font_family_no_default` keys.

This should help eliminate translation errors, as currently many languages have incorrect translation for those keys, even `en` has an incorrectly placed parenthesis there, resulting in this displayed in UI: `Actions Font Family (Default): "Rubik")`.

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by flavioislima** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/doc/cla.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by jjanuszkiewicz** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jjanuszkiewicz** [comment]
recheck

**Review by arielj — APPROVED** [review]
looks good to me

it will require some work from translators to re-add the translation, but it's a needed change to make them better

**Comment by jjanuszkiewicz** [comment]
I thought to add a Polish translation myself, and to add all remaining translations as suggestions, as this is just a technical change and not really any new translation. I can do that as soon as this is merged and pushed to Weblate.

**Pull request merged**
