### PR TITLE
Fixed electron-builder config

### PR DESCRIPTION
**Pull request by Nocccer**
Fix for issue #467 
----------------------------------

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] works for .deb
- [x] works for appImage
- [ ] works for pacman
- [ ] works for win
- [ ] works for mac
-----------------------------------------------

- [ ] Created / Updated Tests
- [ ] Created / Updated documentation

Tested on a Clean Install with AppImage:
- [x] Login
- [x] Download a Game
- [ ] Import a Game
- [ ] Launch Default config
- [ ] Launch Personalized Config
- [x] Launch wine
- [x] Launch Proton
- [ ] Launch Custom Proton
- [x] Launch Tools (Winetricks and Winecfg)
- [x] Uninstall Game
- [ ] Move Game
- [x] Languages (Test if no translation stopped working)

### CODE REVIEW

**Comment by Nocccer** [comment]
@flavioislima @dragonDScript this fix should resolve issue #467. Can't test .pacman, win and mac. 
Will test the launcher itself tomorrow.

**Comment by flavioislima** [comment]
This will prevent the binary to be unpacked but won't fix the issue because the binary will still be there. You can keep this but I think the best way to solve this is to add a rm command when building heroic for Linux.

**Comment by dragonDScript** [comment]
You can also use the files flag to ignore and include certain files in the project.

**Review by dragonDScript — APPROVED** [review]

**Comment by flavioislima** [comment]
> You can also use the files flag to ignore and include certain files in the project.
> 
> Then, move bin/${process.platform} to the resources folder or asarUnpack.
> 
> Aside from that, soft-approving this.

You might do that then @Nocccer, that should fix the issue for good.

**Comment by Nocccer** [comment]
@dragonDScript can you take my branch and implement it?

**Comment by Nocccer** [comment]
@flavioislima @dragonDScript  i think i fixed it now. You can use files for every os entry, too.
Also fixed the reverted jest.config.js split for backend and frontend.

**Review by flavioislima — APPROVED** [review]
Great! I didn't know about the files flag. That's good. Next version should be smaller because we now have 3 different binaries there.

**Comment by Nocccer** [comment]
Tested app with .deb pacakge. 
The game i tried printed a wine error with dxvk missing. Also installed and removed it. So it still finds the legendary executable.

**Comment by flavioislima** [comment]
> Tested app with .deb pacakge. 
> The game i tried printed a wine error with dxvk missing. Also installed and removed it. So it still finds the legendary executable.

Yeah, if it can't find the legendary binary it won't even go to the library page. It will stuck in the login page.

**Review by dragonDScript — APPROVED** [review]
LGTM now

**Pull request merged**
