### PR TITLE
[GOG]: Switch to Galaxy way of loading library

### PR DESCRIPTION
**Pull request by imLinguin**
This is a test of trying to replicate how GOG Galaxy loads the library.  

We achieve this using galaxy-library endpoint which contains games from all connected integrations (updated by client), and GOG (updated internally). We filter out all the gog games and use those.  
If we decided to go hardcore we could maybe support those integrations in the future in some way.   

Of course this can be further extended in terms of caching and deciding whether to fetch new data for games.

One proposition is to verify if we have up to date data when opening the game page.  
~~For now I'm marking it as wip (library pagination is still to be done)~~

Additionally the galaxy-library endpoint provides us with certificates that somehow in pair with GOG access token allow us to get data from gamesdb that would return 404 otherwise.  
Additionally I reduced IO traffic when pulling the library thanks to allowing to temporarily offload the CacheStore to memory, and then sync it to drive after all operations.  

This PR also adds new field `installable` to GameInfo. Preventing Cannot get game info errors for goodie packs.

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by imLinguin** [comment]
This PR also removes duplicated `getGamesdbData` function from `wiki_game_info` utils

**Comment by imLinguin** [comment]
New `not installable` feature:

image

image
image

**Review by flavioislima — COMMENTED** [review]
Looks cool, will do some testing

**Review by flavioislima — APPROVED** [review]
Tested here and everything looks good:

- [x] List games
- [x] Install
- [x] Launch
- [x] Uninstall

During the cache update, I got some missing/wrong information but then it updated it automatically after a few seconds. I think that is expected.

**Comment by flavioislima** [comment]
@imLinguin I think this one is fine to merge if you want to.

**Pull request merged**
