### PR TITLE
Try to prevent login using the store webview

### PR DESCRIPTION
**Pull request by arielj**
Many users log in using the store webview when something fails in the login, creating more issues because then the user is already logged in the store but not in Heroic.

This PR adds a `Log in` dialog/warning covering the page that would take the user to the login process we want for each store. This fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1870

https://user-images.githubusercontent.com/188464/197361806-68c526c7-62c2-4336-9ffb-db75db1235ed.mp4

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Review by CommandMC — COMMENTED** [review]
First of all, I like it. The "Log in" button is basic, but it works.

That being said, I have some concerns:
While testing this locally, I noticed that the button was "trailing behind" when resizing the window, making it possible to still click the actual button below it if you're fast enough
There are also other ways of getting to the login prompt, for example by trying to check out in GOG. I also fear that this'll break with a site redesign

Maybe disabling the "Stores" tab for the respective store if you're not logged in would be easier

**Comment by arielj** [comment]
> First of all, I like it. The "Log in" button is basic, but it works.
> 
> That being said, I have some concerns: While testing this locally, I noticed that the button was "trailing behind" when resizing the window, making it possible to still click the actual button below it if you're fast enough There are also other ways of getting to the login prompt, for example by trying to check out in GOG. I also fear that this'll break with a site redesign
> 
> Maybe disabling the "Stores" tab for the respective store if you're not logged in would be easier

I agree that a user can find ways to break this like resizing the window or going somewhere else ignoring the `Log In` button, but if you actually try to be fast enough to click the login button while resizing then you are looking to have an issue on purpose.

I think I can detect when the user navigates to any of the checkout pages and redirect them to the login if they are not logged in (my first implementation was detecting the current URL after a user change but had to discard that because the GOG login is not a separated URL, but I can make a combination of both strategies)

I thought about disabling the stores, I just didn't know if we really wanted to do that (I don't know what was the reason to have the stores display when logged out in the first place).

**Comment by CommandMC** [comment]
> but if you actually try to be fast enough to click the login button while resizing then you are looking to have an issue on purpose

Speaking from unpleasant past experiences, I'd never underestimate how determined a user is to breaking your software

> I don't know what was the reason to have the stores display when logged out in the first place

I don't think there is a reason.
This, to me, sounds much easier than adding this element and watching for certain URL/navigation changes, on top of it of course not breaking when sites change

**Comment by flavioislima** [comment]
A more simple approach would be to hide the Store until the user is logged in.
Or show a warning window if the user clicks on the store link but it is not logged in.
Like:
`Are you trying to log in? Click here to Login to your GOG/Epic account.`
And another button saying: `I am just looking at the store, continue.`

I think having this button is not sustainable in the long run because both epic and GOG can change their layout and this will break on our end as well, so we would need another update to fix that.

**Comment by arielj** [comment]
I'll wait until `feat/replace_native_dialogs` is merged so I can use that feature for this to make a dialog on top of the stores to prevent users from logging in there

**Comment by arielj** [comment]
@flavioislima @CommandMC I replaced this with a dialog component covering the screen, I think it looks better now and it's more obvious to the user. They can still close it and navigate the stores.

**Review by flavioislima — APPROVED** [review]
LGTM!
Now looks a lot better imo 👍🏽

**Pull request merged**
