### PR TITLE
[GOG!]: move authorization to gogdl

### PR DESCRIPTION
**Pull request by imLinguin**
This is a breaking change, making older versions of Heroic not able to use this config

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [x] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by arielj** [comment]
I'm having errors with this PR. When I try to login I have this in the console:

```
(16:09:22) INFO:    [Gog]:              Running command: /home/ariel/dev/oss/HeroicGamesLauncher/public/bin/linux/gogdl --auth-config-path /home/ariel/.config/heroic/gog_store/auth.json auth --code <redacted>
Error occurred in handler for 'authGOG': SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at GOGUser.login (/home/ariel/dev/oss/HeroicGamesLauncher/build/electron/main.c0984f1b.js:598:24)
    at async node:electron/js2c/browser_init:2:97553
```

And this in the gogdl logs:

```
[4/2/2023, 16:09:22] /home/ariel/dev/oss/HeroicGamesLauncher/public/bin/linux/gogdl --auth-config-path /home/ariel/.config/heroic/gog_store/auth.json auth --code <redacted>
Traceback (most recent call last):
  File "gogdl/cli.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "gogdl/auth.py", line 15, in <module>
  File "gogdl/auth.py", line 39, in AuthorizationManager
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
[764057] Failed to execute script 'cli' due to unhandled exception!
```

**Comment by imLinguin** [comment]
I thought that was correct, weird thing because it worked for me :D
removed it here
https://github.com/Heroic-Games-Launcher/heroic-gogdl/actions/runs/4093041846/jobs/7058196908

I'll improve types definitons in gogdl soon due to refactor

**Comment by arielj** [comment]
When I try to download a game, the install dialog loads forever, I have this in the console:

```
(16:12:59) INFO:    [Gog]:              Running command: /home/ariel/dev/oss/HeroicGamesLauncher/public/bin/linux/gogdl --auth-config-path /home/ariel/.config/heroic/gog_store/auth.json auth
(16:12:59) DEBUG:   [Backend]:          {"free":130321694720,"diskSize":982900588544,"message":"121.37 GiB / 915.4 GiB","validPath":true}
(16:12:59) DEBUG:   [Backend]:          {"free":130312667136,"diskSize":982900588544,"message":"121.36 GiB / 915.4 GiB","validPath":true}
(16:13:00) ERROR:   [Gog]:              SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at GOGUser.getCredentials (/home/ariel/dev/oss/HeroicGamesLauncher/build/electron/main.c0984f1b.js:646:17)
    at async _GOGLibrary.getInstallInfo (/home/ariel/dev/oss/HeroicGamesLauncher/build/electron/main.c0984f1b.js:2507:25)
    at async _GOGGame.getInstallInfo (/home/ariel/dev/oss/HeroicGamesLauncher/build/electron/main.c0984f1b.js:4007:18)
    at async /home/ariel/dev/oss/HeroicGamesLauncher/build/electron/main.c0984f1b.js:14193:20
    at async node:electron/js2c/browser_init:2:97553
(16:13:00) ERROR:   [Gog]:              SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at GOGUser.getCredentials (/home/ariel/dev/oss/HeroicGamesLauncher/build/electron/main.c0984f1b.js:646:17)
    at async _GOGLibrary.getInstallInfo (/home/ariel/dev/oss/HeroicGamesLauncher/build/electron/main.c0984f1b.js:2507:25)
    at async _GOGGame.getInstallInfo (/home/ariel/dev/oss/HeroicGamesLauncher/build/electron/main.c0984f1b.js:4007:18)
    at async /home/ariel/dev/oss/HeroicGamesLauncher/build/electron/main.c0984f1b.js:14193:20
    at async node:electron/js2c/browser_init:2:97553
```

and the same error in gogdl's log as the previous message

**Comment by arielj** [comment]
> I thought that was correct, weird thing because it worked for me :D removed it here https://github.com/Heroic-Games-Launcher/heroic-gogdl/actions/runs/4093041846/jobs/7058196908
> 
> I'll improve types definitons in gogdl soon due to refactor

Using that binary I can get the game install info, but if I log out I can't log in, this is the error from gogdl with the updated binary

```
[4/2/2023, 16:18:46] /home/ariel/Descargas/gogdl --auth-config-path /home/ariel/.config/heroic/gog_store/auth.json auth --code <redacted>
Traceback (most recent call last):
  File "gogdl/cli.py", line 51, in <module>
  File "gogdl/cli.py", line 30, in main
  File "gogdl/api.py", line 22, in __init__
TypeError: 'NoneType' object is not subscriptable
[768766] Failed to execute script 'cli' due to unhandled exception!
```

**Comment by imLinguin** [comment]
I'll fix those in a moment   
I also need to move cloud saves to use new token management

**Comment by imLinguin** [comment]
Everything should be working now

**Comment by arielj** [comment]
I can log in now and get the download info, but when I try to download a game it complains about the missing token

```
[4/2/2023, 18:00:21] /home/ariel/dev/oss/HeroicGamesLauncher/public/bin/linux/gogdl --auth-config-path /home/ariel/.config/heroic/gog_store/auth.json download 1224713507 --platform windows --path=/home/ariel/Games/Heroic --skip-dlcs --lang=en-US
usage: gogdl download [-h] [--lang LANG] [--build BUILD] --path PATH
                      [--platform {windows,osx,linux}] [--with-dlcs]
                      [--skip-dlcs] --token TOKEN
                      [--max-workers WORKERS_COUNT]
                      id
gogdl download: error: the following arguments are required: --token/-t
```

**Comment by arielj** [comment]
@imLinguin do I need to do anything special to add the new binaries? I think that, for the linux one I have to give it exec permissions, but I don't know if I need to do anything for the mac and windows ones

**Comment by flavioislima** [comment]
@arielj i think since you are on that. We should actually start doind the chmod thing on heroic. Because it is easy for us to forget that before sending the binaries.
Check how we are doing when launching sideload games.
Except that we do not need to revert it back.

So I think when heroic launches we check the permissions on the file and set it to executable. That would be ideal.

Especially since some people are adding alternative binaries without setting the executable permissions and then it breaks heroic.

**Comment by arielj** [comment]
> @arielj i think since you are on that. We should actually start doind the chmod thing on heroic. Because it is easy for us to forget that before sending the binaries. Check how we are doing when launching sideload games. Except that we do not need to revert it back.
> 
> So I think when heroic launches we check the permissions on the file and set it to executable. That would be ideal.
> 
> Especially since some people are adding alternative binaries without setting the executable permissions and then it breaks heroic.

makes sense for us to change the permissions, yes

I understand we only need that for linux and mac, right?

**Comment by imLinguin** [comment]
Yes, we only need to mark binaries as executable on Linux and Mac

**Review by arielj — APPROVED** [review]

**Comment by arielj** [comment]
ok, I'm merging this one, I installed 13 GOG games in a row for like 4 hours, I only had one issue but because my internet connection died in the middle

**Pull request merged**
