### PR TITLE
Update settings section

### PR DESCRIPTION
**Pull request by wiryfuture**
Trying to follow the new Figma design as much as possible.
#768 

Still got some work to do but it's a start.

### CODE REVIEW

**Comment by wiryfuture** [comment]
@dragonDScript

**Comment by dragonDScript** [comment]
Can you post a screenshot of it here?

**Comment by wiryfuture** [comment]
> Can you post a screenshot of it here?


(and game settings)

**Comment by wiryfuture** [comment]
Is there anything (else) we want to prioritise here in particular?
Maybe something to do with the switches?
I'm pretty sure the colours and fonts need a quick catch up to what the current intended design is,
maybe some icons, I'm not sure. 

If you give me a design, I can probably implement it with css.

**Comment by wiryfuture** [comment]
I've added variables for all the colours in the gen5 figma, and ones for the defined fonts because that didn't exist for some reason, which I'm trying to stick to.

I'll do the winecfg/winetricks section and checkboxes and then I'll do some work on the game specific settings, which i think will be a bit more involved because right now, it sucks. It completely covers the screen and has no back button or anything, when it's supposed to look like this:
https://www.figma.com/file/aASC1gR8HHBboSa2awKeiK/Heroic?node-id=1320%3A3055
https://www.figma.com/file/aASC1gR8HHBboSa2awKeiK/Heroic?node-id=1320%3A3055

Most recent iteration:
General settings:
image
image
image

Game specific settings:
image
image

**Comment by wiryfuture** [comment]
Sliders moved to the left 
image

**Comment by wiryfuture** [comment]
Made bottom buttons actual buttons instead of text.
Screenshot_20220119_123107

**Comment by wiryfuture** [comment]
I'm pretty sure I've got the settings page almost completed, now the settings page for individual games needs to be fixed.
Will probably need to change the settings button on the game page component to open a <dialog> box with that game's settings page in it instead of redirecting the whole launcher to it.

**Comment by Nocccer** [comment]
Don't like that the toggle buttons are now on the left side. Right side was perfect in my eyes. Way cleaner aligned.
Also would replace all buttons just with a clickable text. See Log Settings tab --> current log and last log:
image

Dangerous button are red marked.
Also the hover animation of Run exe in prefix looks weird. The grey color does not fit well

**Comment by wiryfuture** [comment]
> Don't like that the toggle buttons are now on the left side. Right side was perfect in my eyes. Way cleaner aligned. Also would replace all buttons just with a clickable text. See Log Settings tab --> current log and last log: image
> 
> Dangerous button are red marked. Also the hover animation of Run exe in prefix looks weird. The grey color does not fit well
> 
> What i like are the new blue colors.

I didn't touch the position of the Current/last log buttons, they must have been changed by a selector for something else (I never knew they were on the right side 😆 )
Also, I'm not very sure about the run exe hover, I'm iterating some colours on it rn.

**Comment by Nocccer** [comment]
> > Don't like that the toggle buttons are now on the left side. Right side was perfect in my eyes. Way cleaner aligned. Also would replace all buttons just with a clickable text. See Log Settings tab --> current log and last log: image
> > Dangerous button are red marked. Also the hover animation of Run exe in prefix looks weird. The grey color does not fit well
> > What i like are the new blue colors.
> 
> I didn't touch the position of the Current/last log buttons, they must have been changed by a selector for something else (I never knew they were on the right side laughing ) Also, I'm not very sure about the run exe hover, I'm iterating some colours on it rn.

Not talking about the current log and last log button. There are fine. Talking about the switches/toggles. You moved them from right to left and taht looks ugly in my eyes. Also most programs have there switches/toggles right side.

**Comment by wiryfuture** [comment]
> > > Don't like that the toggle buttons are now on the left side. Right side was perfect in my eyes. Way cleaner aligned. Also would replace all buttons just with a clickable text. See Log Settings tab --> current log and last log: image
> > > Dangerous button are red marked. Also the hover animation of Run exe in prefix looks weird. The grey color does not fit well
> > > What i like are the new blue colors.
> > 
> > 
> > I didn't touch the position of the Current/last log buttons, they must have been changed by a selector for something else (I never knew they were on the right side laughing ) Also, I'm not very sure about the run exe hover, I'm iterating some colours on it rn.
> 
> Not talking about the current log and last log button. There are fine. Talking about the switches/toggles. You moved them from right to left and taht looks ugly in my eyes. Also most programs have there switches/toggles right side.

Ah. I was working off the figma design, but knowing what people actually think is helpful. Will need more general consensous which side they should be.

**Comment by flavioislima** [comment]
@Nocccer
Yes, it's weird because it's a big change but I also think that it is easier to toggle the correct option since the current design the text and the toggle might be too far away.
I think if we change the toggles for checkbox that would make more sense. Steam settings are like this for instance.

**Comment by wiryfuture** [comment]
> @Nocccer Yes, it's weird because it's a big change but I also think that it is easier to toggle the correct option since the current design the text and the toggle might be too far away. I think if we change the toggles for checkbox that would make more sense. Steam settings are like this for instance.

iirc @Flonky suggested to keep the sliders, so I've kept them for now, I can create an iteration with checkboxes if that would help make a decision?

**Comment by flavioislima** [comment]
@wiryfuture that would be nice. 👍

**Comment by Nocccer** [comment]
I would say if the icon is a checkbox keep it left if it is a slider keep it right.

**Comment by wiryfuture** [comment]
Removed the footer buttons from the wine, other and logs setting pages;
Screenshot_20220131_153502
Screenshot_20220131_153513
Screenshot_20220131_153522
)
image

**Comment by flavioislima** [comment]
Nice!

**Comment by wiryfuture** [comment]
I'm gonna fix the games' settings in a different PR, otherwise this one will get very complicated.

**Comment by wiryfuture** [comment]
So, last changes I'll be making in this PR is unbutton-ifying the footer options to copy to clipboard, clear cache and reset heroic. While i personally don't entirely agree with this decision, I'll be adding the icons and changing it to be just text.
After that, hopefully, this should be ready to ship (unless someone suggests some other changes)

**Comment by flavioislima** [comment]
> So, last changes I'll be making in this PR is unbutton-ifying the footer options to copy to clipboard, clear cache and reset heroic. While i personally don't entirely agree with this decision, I'll be adding the icons and changing it to be just text. After that, hopefully, this should be ready to ship (unless someone suggests some other changes)

Sounds good!

Yes, let's try this design a bit and collect feedback.

One idea I also have right now is to experiment with floating buttons like we have on android and we already have this functionality with the MUI library I believe:
https://mui.com/components/floating-action-button/

**Comment by flavioislima** [comment]
Testing here. Noticed two things:
1. Missing Header on Settings. This is needed since otherwise, the user won't know which setting is being changing if a game setting or the global settings.
2. The Color Orange was replaced by blue (I believe is blue) everywhere. Was this related to the new design in Figma?

**Comment by wiryfuture** [comment]
> Testing here. Noticed two things:
> 1. Missing Header on Settings. This is needed since otherwise, the user won't know which setting is being changing if a game setting or the global settings.
> 2. The Color Orange was replaced by blue (I believe is blue) everywhere. Was this related to the new design in Figma?

I removed the header since I was planning to make the game settings be in a modal (like in the new figma design, where it's missing as well), but won't do that in this PR because of how much it'll need to change. I'll add it back until the game settings page is changed. 

Yeah, I grabbed the colours from the latest figma I design (afaik), but I can change them back if you want me to. I was changing the variable names to make more sense with the figma, and it was difficult to map them over from the old names to the new ones, but I can change the colours back now if necessary.
(That's your choice of preference)

**Comment by flavioislima** [comment]
@wiryfuture let's keep the old Yellow color `(--secondary)`. for selected links and selected Checkboxes.
And get back the Header. And then I think we are good to merge this :)

**Comment by wiryfuture** [comment]
> @wiryfuture let's keep the old Yellow color `(--secondary)`. for selected links and selected Checkboxes. And get back the Header. And then I think we are good to merge this :)

Like this?

**Comment by wiryfuture** [comment]
I want to iconify the footer buttons and then I think this will be good

**Comment by flavioislima** [comment]
Yes, looks good now. We need to implement theming on the next version so we can make this more versatile. But for now, let's keep this as the default one.

**Comment by flavioislima** [comment]
> I want to iconify the footer buttons and then I think this will be good

yes, send a screenshot with the result :)

**Comment by wiryfuture** [comment]
> Yes, looks good now. We need to implement theming on the next version so we can make this more versatile. But for now, let's keep this as the default one.

I think I've made some good variables, so it should be pretty easy now 🥳

**Comment by wiryfuture** [comment]
> > I want to iconify the footer buttons and then I think this will be good
> 
> yes, send a screenshot with the result :)

Not sure if this is exactly what i was expecting but I think it works.

Screenshot_20220202_164921
Screenshot_20220202_164940
Screenshot_20220202_164953
Screenshot_20220202_165005
Screenshot_20220202_165033

**Comment by wiryfuture** [comment]
@flavioislima ready for another review on this

**Comment by Nocccer** [comment]
Can add the button style for copy to clipboard to the bottom buttons of the log page aswell? Also with text

**Comment by wiryfuture** [comment]
> Can add the button style for copy to clipboard to the bottom buttons of the log page aswell? Also with text
> 
> Everything else looked fine for me

**Comment by wiryfuture** [comment]
> Can add the button style for copy to clipboard to the bottom buttons of the log page aswell? Also with text
> 
> Everything else looked fine for me

Is this ok?

**Review by flavioislima — APPROVED** [review]
Looks pretty good now ⚔️

**Pull request merged**
