### PR TITLE
Remove Prettier.

### PR DESCRIPTION
**Pull request by adityaruplaha**
I found that prettier was (still) not set up properly, and was conflicting with some ESLint rules (I couldn't figure out the root cause). I found one of them in #263. 

Also, all the rules we defined in Prettier were available and autofixable in ESLint anyways, so I decided that it was more hassle than it was worth, and removed it. It will also simplify our pre-commit and pre-push workflows.

This is just a proposal so that we can discuss the merits and demerits of this.

----

Functionally, only a few tabs got shifted around and the dangling commas got removed.

### CODE REVIEW

**Comment by adityaruplaha** [comment]
Any comments on this?

**Comment by flavioislima** [comment]
> 
> 
> Any comments on this?

I'll try to take a look later.

**Comment by flavioislima** [comment]
Yeah, I think we might not need prettier then. Like you said, we are using eslint to fix most of the things already.

**Review by flavioislima — DISMISSED** [review]

**Review by flavioislima — APPROVED** [review]
👍

**Pull request merged**
