### PR TITLE
Link EA and Ubisoft Games

### PR DESCRIPTION
**Pull request by flavioislima**
- [x] Add a type to differentiate Origin games from the others.
- [ ] Add option to Link the Origin game from the Install modal.
- [ ] Add option to link the game from the game page.
- [ ] Store install information somewhere.
- [ ] Update launch function to deal with origin games.
- [ ] Update Labels, add Origin warning and information for Windows and Linux.

-------------------------------------------------------------
Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by dragonDScript** [comment]
This would be a great addition :heart: AFAIK you can download Origin games from Epic Games but then you need to launch their Origin client also.

**Comment by adityaruplaha** [comment]
Is using Legendary advisable for this? The end goal isn't clear to me, is it implementing a way to add Origin games into Legendary or are we looking to add deeper Origin integration into Heroic?

**Comment by flavioislima** [comment]
@adityaruplaha the end goal is to implement the legendary feature to link/activate the games on the user account.

**Comment by adityaruplaha** [comment]
> @adityaruplaha the end goal is to implement the legendary feature to link/activate the games on the user account. 

Alright, then this makes sense.

**Comment by flavioislima** [comment]
wont do

**Pull request closed without merging**
