### PR TITLE
[FEAT] Support Custom User Agent for browser apps

### PR DESCRIPTION
**Pull request by flavioislima**
Implements #2757 
Also added a Full-Screen option

userAgent1

Screenshot_20231103_125404

image

Fullscreen setting:
image

Custom UA used for youtube tv: Mozilla/5.0 (PS4; Leanback Shell) Gecko/20100101 Firefox/65.0 LeanbackShell/01.00.01.75 Sony PS4/ (PS4, , no, CH)

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

**Comment by Doc-4** [comment]
Very cool! Thanks for the implementation, looking forward to testing it. Does this also implement spoofing UA client hints? If it doesn't, some sites might see through it.

**Comment by flavioislima** [comment]
> Very cool! Thanks for the implementation, looking forward to testing it. Does this also implement spoofing UA client hints? If it doesn't, some sites might see through it.

it does something similar to the other PR that was linked but I did not tested it. Feel free to test it with the appimage before I merge it and release it.

**Comment by Doc-4** [comment]
Tested with no override, chrome for windows and edge for windows. It may not necessarily be directly related, but this
doesn't do anything to fix accessing sites such as GeForce Now. They don't work at all from the beginning to make the site believe it's stock chrome or edge, UA override or no. 
IMG_20231103_133748

**Comment by flavioislima** [comment]
> Tested with no override, chrome for windows and edge for windows. It may not necessarily be directly related, but this doesn't do anything to fix accessing sites such as GeForce Now. They don't work at all from the beginning to make the site believe it's stock chrome or edge, UA override or no. IMG_20231103_133748

maybe we need to run Heroic with this argument?
`'--spoof-windows'`

Looking at the original code for gfn it seems like it. I will try as well.

But, this won't be a blocker to this PR and we can investigate and improve this further on.

**Comment by flavioislima** [comment]
Can you try this user agent?
`Mozilla/5.0 (Macintosh; Intel Mac OS X 14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36`

**Comment by flavioislima** [comment]
It works for me but it does not show Genshin Impact. 
image

So maybe this spoof windows flag is not working or genshin Impact was removed from it. 
I have no idea.

**Comment by Doc-4** [comment]
> It works for me but it does not show Genshin Impact. image
> 
> So maybe this spoof windows flag is not working or genshin Impact was removed from it. I have no idea.

The aforementioned issue in GFN was followed up by spoof windows no longer being maintained due to it breaking due to something changed and the developer not wanting to continue maintaining the function. It's up to someone else to figure out exactly how to fix it, some people more technically knowledgeable about electron were discussing potential solutions in the rest of that issue, but since the developer isn't going to implement them, if we want that functionality it would have to be someone else.

**Comment by flavioislima** [comment]
@Doc-4 I am not an electron expert as well unfortunatelly 🤷🏽 
Well, at least it is working, I cannot guarantee that every website and game will work though.

**Comment by Doc-4** [comment]
> @Doc-4 I am not an electron expert as well unfortunatelly 🤷🏽 Well, at least it is working, I cannot guarantee that every website and game will work though.

Of course, that's understandable. It's still my hope that at some point a solid sandbox solution for web apps will exist. Genshin's a good example of something where this is the best solution, as other solutions on linux require self hosting cloud gaming or unofficial, unauthorized launchers. 
This is the easiest gap to bridge, IMO. And if it's made well for one web app, it'll work for just about any web app that tries to serve an inferior experience to linux.

**Pull request merged**
